import type { StudyPdfLocale } from '@/lib/study-pdf-locales'

type Copy = {
  dueToday: string; newCards: string; startReview: string; reviewAll: string; noDue: string
  localProgress: string; again: string; hard: string; good: string; easy: string
  ratingHint: string; keyboardHint: string; saveFailed: string; priorityQuiz: string
  sessionCount: string; sourceLink: string; resetDone: string; deleteDone: string
  reviewLimit: string; reviewComplete: string; nextReview: string; retryMistakes: string; generationIncomplete: string
}

export const adaptiveStudyCopy: Record<StudyPdfLocale, Copy> = {
  fr: { dueToday: 'À revoir maintenant', newCards: 'Nouvelles cartes', startReview: 'Commencer la révision', reviewAll: 'Réviser quand même', noDue: 'Tout est à jour pour le moment.', localProgress: 'Progression enregistrée sur cet appareil.', again: 'À revoir', hard: 'Difficile', good: 'Bien', easy: 'Facile', ratingHint: 'Oublié ? Choisis « À revoir ». « Difficile » signifie que tu as retrouvé la réponse avec effort.', keyboardHint: 'Espace : réponse · 1 à 4 : évaluer', saveFailed: 'La progression n’a pas pu être enregistrée sur cet appareil.', priorityQuiz: 'Quiz ciblé sur mes difficultés', sessionCount: 'Cartes travaillées', sourceLink: 'Ouvrir la page source', resetDone: 'Progression réinitialisée', deleteDone: 'Cartes supprimées', reviewLimit: 'Jusqu’à 20 cartes par session, les plus urgentes d’abord.', reviewComplete: 'Révision terminée', nextReview: 'Prochaine révision', retryMistakes: 'Revoir mes erreurs', generationIncomplete: 'La génération est incomplète. Aucun quota débité ; réessaie.' },
  en: { dueToday: 'Due now', newCards: 'New cards', startReview: 'Start review', reviewAll: 'Practice anyway', noDue: 'You are up to date for now.', localProgress: 'Progress is saved on this device.', again: 'Again', hard: 'Hard', good: 'Good', easy: 'Easy', ratingHint: 'Forgot it? Choose Again. Hard means you recalled it with effort.', keyboardHint: 'Space: reveal · 1–4: rate', saveFailed: 'Progress could not be saved on this device.', priorityQuiz: 'Quiz on my difficult topics', sessionCount: 'Cards studied', sourceLink: 'Open source page', resetDone: 'Progress reset', deleteDone: 'Cards deleted', reviewLimit: 'Up to 20 cards per session, most urgent first.', reviewComplete: 'Review complete', nextReview: 'Next review', retryMistakes: 'Retry missed questions', generationIncomplete: 'Generation was incomplete. No quota was used. Try again.' },
  es: { dueToday: 'Para repasar ahora', newCards: 'Tarjetas nuevas', startReview: 'Empezar el repaso', reviewAll: 'Practicar igualmente', noDue: 'Por ahora estás al día.', localProgress: 'El progreso se guarda en este dispositivo.', again: 'Otra vez', hard: 'Difícil', good: 'Bien', easy: 'Fácil', ratingHint: '¿La olvidaste? Elige «Otra vez». «Difícil» significa que la recordaste con esfuerzo.', keyboardHint: 'Espacio: mostrar · 1–4: evaluar', saveFailed: 'No se pudo guardar el progreso en este dispositivo.', priorityQuiz: 'Quiz sobre mis dificultades', sessionCount: 'Tarjetas repasadas', sourceLink: 'Abrir la página fuente', resetDone: 'Progreso reiniciado', deleteDone: 'Tarjetas eliminadas', reviewLimit: 'Hasta 20 tarjetas por sesión, primero las más urgentes.', reviewComplete: 'Repaso terminado', nextReview: 'Próximo repaso', retryMistakes: 'Repetir mis errores', generationIncomplete: 'La generación quedó incompleta. No se descontó cuota. Inténtalo de nuevo.' },
  de: { dueToday: 'Jetzt fällig', newCards: 'Neue Karten', startReview: 'Wiederholung starten', reviewAll: 'Trotzdem üben', noDue: 'Im Moment bist du auf dem Laufenden.', localProgress: 'Der Lernstand wird auf diesem Gerät gespeichert.', again: 'Noch einmal', hard: 'Schwer', good: 'Gut', easy: 'Leicht', ratingHint: 'Vergessen? Wähle „Noch einmal“. „Schwer“ bedeutet, dass du dich mit Mühe erinnert hast.', keyboardHint: 'Leertaste: Antwort · 1–4: bewerten', saveFailed: 'Der Lernstand konnte auf diesem Gerät nicht gespeichert werden.', priorityQuiz: 'Quiz zu meinen Schwierigkeiten', sessionCount: 'Geübte Karten', sourceLink: 'Quellseite öffnen', resetDone: 'Lernstand zurückgesetzt', deleteDone: 'Karten gelöscht', reviewLimit: 'Bis zu 20 Karten pro Einheit, die dringendsten zuerst.', reviewComplete: 'Wiederholung abgeschlossen', nextReview: 'Nächste Wiederholung', retryMistakes: 'Fehler erneut üben', generationIncomplete: 'Die Erstellung war unvollständig. Kein Kontingent verbraucht. Bitte erneut versuchen.' },
  it: { dueToday: 'Da ripassare ora', newCards: 'Schede nuove', startReview: 'Inizia il ripasso', reviewAll: 'Ripassa comunque', noDue: 'Per ora sei in pari.', localProgress: 'I progressi sono salvati su questo dispositivo.', again: 'Ancora', hard: 'Difficile', good: 'Bene', easy: 'Facile', ratingHint: 'Dimenticata? Scegli «Ancora». «Difficile» significa che l’hai ricordata con fatica.', keyboardHint: 'Spazio: risposta · 1–4: valuta', saveFailed: 'Impossibile salvare i progressi su questo dispositivo.', priorityQuiz: 'Quiz sulle mie difficoltà', sessionCount: 'Schede studiate', sourceLink: 'Apri la pagina fonte', resetDone: 'Progressi azzerati', deleteDone: 'Schede eliminate', reviewLimit: 'Fino a 20 schede per sessione, prima le più urgenti.', reviewComplete: 'Ripasso completato', nextReview: 'Prossimo ripasso', retryMistakes: 'Riprova gli errori', generationIncomplete: 'La generazione è incompleta. Nessuna quota addebitata. Riprova.' },
  pt: { dueToday: 'Para rever agora', newCards: 'Cartões novos', startReview: 'Começar revisão', reviewAll: 'Praticar na mesma', noDue: 'Estás em dia por agora.', localProgress: 'O progresso fica guardado neste dispositivo.', again: 'Outra vez', hard: 'Difícil', good: 'Bem', easy: 'Fácil', ratingHint: 'Esqueceste-te? Escolhe «Outra vez». «Difícil» significa que te lembraste com esforço.', keyboardHint: 'Espaço: resposta · 1–4: avaliar', saveFailed: 'Não foi possível guardar o progresso neste dispositivo.', priorityQuiz: 'Quiz sobre as minhas dificuldades', sessionCount: 'Cartões revistos', sourceLink: 'Abrir página de origem', resetDone: 'Progresso reposto', deleteDone: 'Cartões eliminados', reviewLimit: 'Até 20 cartões por sessão, os mais urgentes primeiro.', reviewComplete: 'Revisão concluída', nextReview: 'Próxima revisão', retryMistakes: 'Repetir os erros', generationIncomplete: 'A geração ficou incompleta. Nenhuma quota foi usada. Tenta novamente.' },
  zh: { dueToday: '现在需要复习', newCards: '新卡片', startReview: '开始复习', reviewAll: '仍要练习', noDue: '目前已完成所有到期复习。', localProgress: '学习进度保存在此设备上。', again: '再来一次', hard: '困难', good: '良好', easy: '轻松', ratingHint: '忘记了就选“再来一次”；“困难”表示费力但仍想起了答案。', keyboardHint: '空格：显示答案 · 1–4：评分', saveFailed: '无法在此设备上保存学习进度。', priorityQuiz: '针对薄弱知识点测验', sessionCount: '已学习卡片', sourceLink: '打开来源页面', resetDone: '学习进度已重置', deleteDone: '卡片已删除', reviewLimit: '每轮最多20张，优先复习最紧急的卡片。', reviewComplete: '复习完成', nextReview: '下次复习', retryMistakes: '重做错题', generationIncomplete: '生成未完成。未扣除额度。请重试。' },
  ja: { dueToday: '今すぐ復習', newCards: '新しいカード', startReview: '復習を始める', reviewAll: '追加で練習', noDue: '今のところ復習は完了です。', localProgress: '学習履歴はこの端末に保存されます。', again: 'もう一度', hard: '難しい', good: 'できた', easy: '簡単', ratingHint: '忘れた場合は「もう一度」。 「難しい」は努力して思い出せた場合に選びます。', keyboardHint: 'スペース：答え · 1～4：評価', saveFailed: 'この端末に学習履歴を保存できませんでした。', priorityQuiz: '苦手分野のクイズ', sessionCount: '学習したカード', sourceLink: '出典ページを開く', resetDone: '学習履歴をリセットしました', deleteDone: 'カードを削除しました', reviewLimit: '1回最大20枚。優先度の高いカードから復習します。', reviewComplete: '復習完了', nextReview: '次の復習', retryMistakes: '間違えた問題を再挑戦', generationIncomplete: '生成が完了しませんでした。利用枠は消費されていません。再試行してください。' },
  ar: { dueToday: 'مستحقة الآن', newCards: 'بطاقات جديدة', startReview: 'ابدأ المراجعة', reviewAll: 'تدرّب على أي حال', noDue: 'أنهيت المراجعات المستحقة حاليًا.', localProgress: 'يُحفظ تقدمك على هذا الجهاز.', again: 'مرة أخرى', hard: 'صعب', good: 'جيد', easy: 'سهل', ratingHint: 'هل نسيت الإجابة؟ اختر «مرة أخرى». «صعب» يعني أنك تذكرتها بعد جهد.', keyboardHint: 'مسافة: أظهر الإجابة · ١–٤: قيّم', saveFailed: 'تعذر حفظ تقدمك على هذا الجهاز.', priorityQuiz: 'اختبار لنقاط ضعفي', sessionCount: 'بطاقات تمت مراجعتها', sourceLink: 'افتح صفحة المصدر', resetDone: 'أُعيد ضبط التقدم', deleteDone: 'حُذفت البطاقات', reviewLimit: 'حتى ٢٠ بطاقة في الجلسة، والأكثر إلحاحًا أولًا.', reviewComplete: 'اكتملت المراجعة', nextReview: 'المراجعة التالية', retryMistakes: 'أعد الأسئلة الخاطئة', generationIncomplete: 'لم يكتمل الإنشاء. لم تُخصم أي حصة. حاول مجددًا.' },
}
