import type { SeoLocale } from '@/lib/seo-locales'

type LandingExperienceCopy = {
  hero: { lead: string; accent: string; upload: string; note: string; how: string }
  studio: {
    file: string; ready: string; demo: string; workspace: string; documents: string; study: string; cards: string
    chapter: string; topic: string; tabs: [string, string, string]; summaryLabel: string; summary: string
    keyIdeas: [string, string]; sourceLabel: string; source: string; sourceNote: string
    cardLabel: string; cardQuestion: string; cardAnswer: string; reveal: string; hide: string
    quizLabel: string; quizQuestion: string; quizAnswers: [string, string, string]; correct: string; incorrect: string
  }
  overview: { eyebrow: string; title: string; description: string; trust: [string, string, string] }
  method: { eyebrow: string; first: string; accent: string; last: string; description: string; action: string; step: string; titles: [string, string, string] }
  moments: { eyebrow: string; first: string; accent: string; description: string; labels: [string, string, string, string]; descriptions: [string, string, string, string]; sampleLabels: [string, string, string, string]; samples: [string, string, string, string] }
  tools: { eyebrow: string; first: string; accent: string; description: string; action: string; textTitle: string; textDescription: string; textAction: string; organizeTitle: string; organizeDescription: string; organizeAction: string; note: string; example: string; thisWeek: string; tasks: [string, string, string]; progress: string }
  pricing: { eyebrow: string; first: string; accent: string; description: string }
  faq: { first: string; accent: string; cancelQuestion: string; cancelAnswer: string }
  cta: { first: string; accent: string; description: string; action: string }
  footer: { description: string; explore: string; studio: string; tools: string; inspect: string; pricing: string; privacy: string; terms: string; contact: string }
}

export const landingExperienceCopy: Record<SeoLocale, LandingExperienceCopy> = {
  en: {
    hero: { lead: 'Your course PDF,', accent: 'ready to study.', upload: 'Start with your PDF', note: '7-day trial, no card required · PDF with selectable text', how: 'See how it works' },
    studio: { file: 'Cell biology.pdf', ready: 'Document ready to study', demo: 'Interactive demo', workspace: 'My workspace', documents: 'Documents', study: 'Study', cards: 'Cards', chapter: 'Chapter 04 · Science', topic: 'The cell membrane', tabs: ['Summary', 'Flashcards', 'Quiz'], summaryLabel: 'The essentials, clearly', summary: 'The cell membrane separates the cell from its surroundings and regulates exchanges. Its flexible structure is a phospholipid bilayer.', keyIdeas: ['A selective barrier protects the inside of the cell.', 'Membrane proteins help certain molecules cross.'], sourceLabel: 'Demo source excerpt', source: 'The plasma membrane consists of a phospholipid bilayer. It separates the inside of the cell from its surroundings and participates in exchanges.', sourceNote: 'The summary stays connected to the course text so you can check each idea.', cardLabel: 'Active recall · Card 01', cardQuestion: 'What is the main role of the cell membrane?', cardAnswer: 'It controls exchanges between the cell and its surroundings.', reveal: 'Show answer', hide: 'Show question', quizLabel: 'Check what you remember · Question 01', quizQuestion: 'What structure forms the membrane barrier?', quizAnswers: ['A phospholipid bilayer', 'A single layer of proteins', 'A cellulose wall'], correct: 'Correct. The bilayer forms the basis of this barrier.', incorrect: 'Not quite. Review the passage about the phospholipid bilayer.' },
    overview: { eyebrow: 'One space to understand and study', title: 'After upload, everything is in one place.', description: 'Read the summary, ask about your document and test your understanding at your own pace.', trust: ['Notes, cards and quizzes in one place', 'Interface in nine languages', 'Your documents available in your account'] },
    method: { eyebrow: 'A different way to study', first: 'Reading is good.', accent: 'Remembering', last: 'is better.', description: 'When courses pile up, a clear summary and a few focused questions help you move from reading to practice.', action: 'Try it with my course', step: 'Step', titles: ['Upload your course', 'See the essentials', 'Put it into practice'] },
    moments: { eyebrow: 'Inside CramDesk', first: 'Four moments to', accent: 'learn better.', description: 'Every tool follows the same course and helps you decide what to understand, remember or revisit.', labels: ['Understand.', 'Remember.', 'Test yourself.', 'Go deeper.'], descriptions: ['A summary and a simpler explanation help you grasp key ideas before memorising them.', 'Question-and-answer cards help you practise active recall at your own pace.', 'Quizzes based on your document reveal the passages worth revisiting.', 'Ask a question about the course and get an answer grounded in the extracted text.'], sampleLabels: ['Key idea', 'Question 01', 'Your turn', 'In the chat'], samples: ['A flexible membrane regulates exchanges between the cell and its surroundings.', 'What does the cell membrane do?', 'Choose an answer and see what to review.', '“Can you explain the bilayer simply?”'] },
    tools: { eyebrow: 'Free tools · No account', first: 'Prepare your PDF.', accent: 'Then study it.', description: 'Merge, extract or rearrange pages in your browser before you start revising. Your files stay on your device.', action: 'Open free PDF tools', textTitle: 'Need to find a concept?', textDescription: 'Inspect pages, search the text and download it locally.', textAction: 'Explore PDF text', organizeTitle: 'Need to reorder pages?', organizeDescription: 'Move pages visually and download the new PDF.', organizeAction: 'Organize my PDF', note: 'No sign-up or payment card. These free tools run in your browser.', example: 'Example workflow', thisWeek: 'Before studying', tasks: ['Prepare the pages', 'Find the key passage', 'Practise with your course'], progress: 'Ready for a focused study session.' },
    pricing: { eyebrow: 'Clear pricing', first: 'A workspace for', accent: 'every study pace.', description: 'Start with a 7-day trial without a payment card. Then choose the volume that suits you.' },
    faq: { first: 'Before you', accent: 'get started.', cancelQuestion: 'Can I cancel my subscription?', cancelAnswer: 'Yes. You can manage or cancel your subscription from your billing area.' },
    cta: { first: 'Your course can become', accent: 'your best study session.', description: 'Try CramDesk for seven days without a payment card.', action: 'Upload my PDF' },
    footer: { description: 'A clearer space to understand your course and practise at your own pace.', explore: 'Explore', studio: 'The workspace', tools: 'Free PDF tools', inspect: 'Explore a PDF', pricing: 'Pricing', privacy: 'Privacy', terms: 'Terms', contact: 'Contact' },
  },
  es: {
    hero: { lead: 'Tu PDF de clase,', accent: 'listo para repasar.', upload: 'Empieza con tu PDF', note: '7 días de prueba sin tarjeta · PDF con texto seleccionable', how: 'Ver cómo funciona' },
    studio: { file: 'Biología celular.pdf', ready: 'Documento listo para repasar', demo: 'Demostración interactiva', workspace: 'Mi espacio', documents: 'Documentos', study: 'Repasar', cards: 'Tarjetas', chapter: 'Capítulo 04 · Ciencias', topic: 'La membrana celular', tabs: ['Resumen', 'Tarjetas', 'Cuestionario'], summaryLabel: 'Lo esencial, con claridad', summary: 'La membrana celular separa la célula de su entorno y regula los intercambios. Su estructura flexible es una bicapa de fosfolípidos.', keyIdeas: ['Una barrera selectiva protege el interior de la célula.', 'Las proteínas de membrana ayudan a ciertas moléculas a atravesarla.'], sourceLabel: 'Fragmento de demostración', source: 'La membrana plasmática está formada por una bicapa de fosfolípidos. Separa el interior celular del medio exterior y participa en los intercambios.', sourceNote: 'El resumen sigue vinculado al texto para que puedas comprobar cada idea.', cardLabel: 'Recuerdo activo · Tarjeta 01', cardQuestion: '¿Cuál es la función principal de la membrana celular?', cardAnswer: 'Controla los intercambios entre la célula y su entorno.', reveal: 'Ver respuesta', hide: 'Ver pregunta', quizLabel: 'Comprueba lo que recuerdas · Pregunta 01', quizQuestion: '¿Qué estructura forma la barrera de la membrana?', quizAnswers: ['Una bicapa de fosfolípidos', 'Una sola capa de proteínas', 'Una pared de celulosa'], correct: 'Correcto. La bicapa es la base de esta barrera.', incorrect: 'Casi. Vuelve al pasaje sobre la bicapa de fosfolípidos.' },
    overview: { eyebrow: 'Un espacio para comprender y repasar', title: 'Después de subirlo, todo está en un mismo lugar.', description: 'Consulta el resumen, pregunta sobre tu documento y pon a prueba tu comprensión a tu ritmo.', trust: ['Apuntes, tarjetas y cuestionarios juntos', 'Interfaz en nueve idiomas', 'Documentos disponibles en tu cuenta'] },
    method: { eyebrow: 'Otra forma de estudiar', first: 'Leer está bien.', accent: 'Recordar', last: 'es mejor.', description: 'Cuando se acumulan los apuntes, un resumen claro y unas preguntas concretas te ayudan a pasar de la lectura a la práctica.', action: 'Probar con mis apuntes', step: 'Paso', titles: ['Sube tus apuntes', 'Ve lo esencial', 'Practica lo aprendido'] },
    moments: { eyebrow: 'Dentro de CramDesk', first: 'Cuatro momentos para', accent: 'aprender mejor.', description: 'Todas las herramientas siguen el mismo curso y te ayudan a comprender, recordar o volver sobre lo importante.', labels: ['Comprender.', 'Memorizar.', 'Ponerte a prueba.', 'Profundizar.'], descriptions: ['Un resumen y una explicación más sencilla te ayudan a entender antes de memorizar.', 'Las tarjetas de preguntas y respuestas te permiten practicar el recuerdo activo.', 'Los cuestionarios basados en tu documento señalan qué partes conviene repasar.', 'Haz una pregunta sobre el curso y recibe una respuesta basada en el texto extraído.'], sampleLabels: ['Idea clave', 'Pregunta 01', 'Tu turno', 'En el chat'], samples: ['Una membrana flexible regula los intercambios entre la célula y su entorno.', '¿Qué función tiene la membrana celular?', 'Elige una respuesta y descubre qué debes repasar.', '«¿Puedes explicarme la bicapa de forma sencilla?»'] },
    tools: { eyebrow: 'Herramientas gratis · Sin cuenta', first: 'Prepara tu PDF.', accent: 'Después, repasa.', description: 'Une, extrae o reordena páginas en tu navegador antes de estudiar. Los archivos permanecen en tu dispositivo.', action: 'Abrir herramientas PDF gratuitas', textTitle: '¿Buscas un concepto?', textDescription: 'Consulta las páginas, busca en el texto y descárgalo localmente.', textAction: 'Explorar el texto del PDF', organizeTitle: '¿Hay páginas desordenadas?', organizeDescription: 'Muévelas visualmente y descarga el nuevo PDF.', organizeAction: 'Organizar mi PDF', note: 'Sin registro ni tarjeta. Estas herramientas funcionan en tu navegador.', example: 'Ejemplo de proceso', thisWeek: 'Antes de repasar', tasks: ['Preparar las páginas', 'Encontrar el pasaje clave', 'Practicar con tus apuntes'], progress: 'Todo listo para una sesión de repaso.' },
    pricing: { eyebrow: 'Precios claros', first: 'Un espacio para', accent: 'cada ritmo de estudio.', description: 'Empieza con 7 días de prueba sin tarjeta y después elige el volumen que necesites.' },
    faq: { first: 'Antes de', accent: 'empezar.', cancelQuestion: '¿Puedo cancelar mi suscripción?', cancelAnswer: 'Sí. Puedes gestionar o cancelar tu suscripción desde el área de facturación.' },
    cta: { first: 'Tus apuntes pueden convertirse en', accent: 'tu mejor repaso.', description: 'Prueba CramDesk durante 7 días sin tarjeta.', action: 'Subir mi PDF' },
    footer: { description: 'Un espacio más claro para comprender tus apuntes y practicar a tu ritmo.', explore: 'Explorar', studio: 'Espacio de estudio', tools: 'Herramientas PDF gratuitas', inspect: 'Explorar un PDF', pricing: 'Precios', privacy: 'Privacidad', terms: 'Condiciones', contact: 'Contacto' },
  },
  de: {
    hero: { lead: 'Dein Kurs-PDF,', accent: 'bereit zum Lernen.', upload: 'Starte mit deinem PDF', note: '7 Tage kostenlos, ohne Karte · PDF mit auswählbarem Text', how: 'So funktioniert es' },
    studio: { file: 'Zellbiologie.pdf', ready: 'Dokument bereit zum Lernen', demo: 'Interaktive Vorschau', workspace: 'Mein Bereich', documents: 'Dokumente', study: 'Lernen', cards: 'Karten', chapter: 'Kapitel 04 · Naturwissenschaft', topic: 'Die Zellmembran', tabs: ['Zusammenfassung', 'Karteikarten', 'Quiz'], summaryLabel: 'Das Wesentliche auf einen Blick', summary: 'Die Zellmembran trennt die Zelle von ihrer Umgebung und regelt den Stoffaustausch. Ihre flexible Struktur besteht aus einer Phospholipid-Doppelschicht.', keyIdeas: ['Eine selektive Barriere schützt das Zellinnere.', 'Membranproteine helfen bestimmten Molekülen beim Durchtritt.'], sourceLabel: 'Beispielauszug', source: 'Die Plasmamembran besteht aus einer Phospholipid-Doppelschicht. Sie trennt das Zellinnere von der Umgebung und ist am Stoffaustausch beteiligt.', sourceNote: 'Die Zusammenfassung bleibt mit dem Kurstext verknüpft, damit du jede Aussage prüfen kannst.', cardLabel: 'Aktives Erinnern · Karte 01', cardQuestion: 'Was ist die wichtigste Aufgabe der Zellmembran?', cardAnswer: 'Sie regelt den Stoffaustausch zwischen Zelle und Umgebung.', reveal: 'Antwort zeigen', hide: 'Frage zeigen', quizLabel: 'Wissen prüfen · Frage 01', quizQuestion: 'Welche Struktur bildet die Membranbarriere?', quizAnswers: ['Eine Phospholipid-Doppelschicht', 'Eine einzelne Proteinschicht', 'Eine Zellulosewand'], correct: 'Richtig. Die Doppelschicht bildet die Grundlage der Barriere.', incorrect: 'Nicht ganz. Lies die Stelle zur Phospholipid-Doppelschicht noch einmal.' },
    overview: { eyebrow: 'Ein Ort zum Verstehen und Wiederholen', title: 'Nach dem Hochladen ist alles an einem Ort.', description: 'Lies die Zusammenfassung, frage dein Dokument und prüfe dein Verständnis in deinem Tempo.', trust: ['Notizen, Karten und Quizze an einem Ort', 'Oberfläche in neun Sprachen', 'Dokumente in deinem Konto verfügbar'] },
    method: { eyebrow: 'Eine andere Art zu lernen', first: 'Lesen ist gut.', accent: 'Behalten', last: 'ist besser.', description: 'Wenn sich Lernstoff stapelt, helfen eine klare Zusammenfassung und gezielte Fragen beim Schritt vom Lesen zum Üben.', action: 'Mit meinem Kurs ausprobieren', step: 'Schritt', titles: ['Kurs hochladen', 'Das Wesentliche sehen', 'Wissen anwenden'] },
    moments: { eyebrow: 'In CramDesk', first: 'Vier Schritte, um', accent: 'besser zu lernen.', description: 'Alle Werkzeuge folgen demselben Kurs und zeigen, was du verstehen, behalten oder erneut ansehen solltest.', labels: ['Verstehen.', 'Behalten.', 'Wissen testen.', 'Vertiefen.'], descriptions: ['Eine Zusammenfassung und eine einfachere Erklärung helfen dir, wichtige Ideen zu erfassen.', 'Frage-Antwort-Karten trainieren das aktive Erinnern in deinem Tempo.', 'Quizze aus deinem Dokument zeigen dir, welche Stellen du wiederholen solltest.', 'Stelle eine Frage zum Kurs und erhalte eine Antwort auf Grundlage des extrahierten Textes.'], sampleLabels: ['Kernidee', 'Frage 01', 'Du bist dran', 'Im Chat'], samples: ['Eine flexible Membran regelt den Stoffaustausch zwischen Zelle und Umgebung.', 'Welche Aufgabe hat die Zellmembran?', 'Wähle eine Antwort und sieh, was du wiederholen solltest.', '„Kannst du mir die Doppelschicht einfach erklären?“'] },
    tools: { eyebrow: 'Kostenlose Tools · Ohne Konto', first: 'Bereite dein PDF vor.', accent: 'Dann lerne damit.', description: 'Füge Seiten zusammen, extrahiere oder ordne sie im Browser neu. Deine Dateien bleiben auf deinem Gerät.', action: 'Kostenlose PDF-Werkzeuge öffnen', textTitle: 'Suchst du einen Begriff?', textDescription: 'Prüfe Seiten, suche im Text und lade ihn lokal herunter.', textAction: 'PDF-Text erkunden', organizeTitle: 'Seiten in falscher Reihenfolge?', organizeDescription: 'Verschiebe sie visuell und lade das neue PDF herunter.', organizeAction: 'PDF ordnen', note: 'Ohne Anmeldung oder Karte. Die Werkzeuge laufen in deinem Browser.', example: 'Beispielablauf', thisWeek: 'Vor dem Lernen', tasks: ['Seiten vorbereiten', 'Wichtige Stelle finden', 'Mit dem Kurs üben'], progress: 'Bereit für eine konzentrierte Lerneinheit.' },
    pricing: { eyebrow: 'Klare Preise', first: 'Ein Lernbereich für', accent: 'jedes Tempo.', description: 'Beginne mit 7 Tagen Probezeit ohne Zahlungskarte. Wähle danach den passenden Umfang.' },
    faq: { first: 'Bevor du', accent: 'loslegst.', cancelQuestion: 'Kann ich mein Abonnement kündigen?', cancelAnswer: 'Ja. In deinem Abrechnungsbereich kannst du dein Abonnement verwalten oder kündigen.' },
    cta: { first: 'Dein Kurs kann zu', accent: 'deiner besten Wiederholung werden.', description: 'Teste CramDesk sieben Tage lang ohne Zahlungskarte.', action: 'Mein PDF hochladen' },
    footer: { description: 'Ein klarer Raum, um deinen Kurs zu verstehen und in deinem Tempo zu üben.', explore: 'Entdecken', studio: 'Lernbereich', tools: 'Kostenlose PDF-Werkzeuge', inspect: 'PDF erkunden', pricing: 'Preise', privacy: 'Datenschutz', terms: 'Bedingungen', contact: 'Kontakt' },
  },
  it: {
    hero: { lead: 'Il tuo PDF del corso,', accent: 'pronto da studiare.', upload: 'Inizia con il tuo PDF', note: '7 giorni di prova senza carta · PDF con testo selezionabile', how: 'Scopri come funziona' },
    studio: { file: 'Biologia cellulare.pdf', ready: 'Documento pronto per il ripasso', demo: 'Anteprima interattiva', workspace: 'Il mio spazio', documents: 'Documenti', study: 'Ripasso', cards: 'Schede', chapter: 'Capitolo 04 · Scienze', topic: 'La membrana cellulare', tabs: ['Riassunto', 'Flashcard', 'Quiz'], summaryLabel: 'L’essenziale, con chiarezza', summary: 'La membrana cellulare separa la cellula dall’ambiente e regola gli scambi. La sua struttura flessibile è una doppia membrana di fosfolipidi.', keyIdeas: ['Una barriera selettiva protegge l’interno della cellula.', 'Le proteine di membrana aiutano alcune molecole ad attraversarla.'], sourceLabel: 'Estratto dimostrativo', source: 'La membrana plasmatica è formata da un doppio strato di fosfolipidi. Separa l’interno della cellula dall’ambiente esterno e partecipa agli scambi.', sourceNote: 'Il riassunto resta collegato al testo del corso, così puoi verificare ogni concetto.', cardLabel: 'Richiamo attivo · Scheda 01', cardQuestion: 'Qual è il ruolo principale della membrana cellulare?', cardAnswer: 'Controlla gli scambi tra la cellula e l’ambiente.', reveal: 'Mostra la risposta', hide: 'Mostra la domanda', quizLabel: 'Verifica ciò che ricordi · Domanda 01', quizQuestion: 'Quale struttura forma la barriera della membrana?', quizAnswers: ['Un doppio strato di fosfolipidi', 'Un unico strato di proteine', 'Una parete di cellulosa'], correct: 'Esatto. Il doppio strato è la base di questa barriera.', incorrect: 'Non proprio. Rileggi il passaggio sul doppio strato di fosfolipidi.' },
    overview: { eyebrow: 'Uno spazio per capire e ripassare', title: 'Dopo il caricamento, tutto è nello stesso posto.', description: 'Consulta il riassunto, fai domande sul documento e verifica la tua comprensione con i tuoi tempi.', trust: ['Appunti, schede e quiz nello stesso posto', 'Interfaccia in nove lingue', 'Documenti disponibili nel tuo account'] },
    method: { eyebrow: 'Un altro modo di studiare', first: 'Leggere va bene.', accent: 'Ricordare', last: 'è meglio.', description: 'Quando i materiali si accumulano, un riassunto chiaro e poche domande mirate aiutano a passare dalla lettura alla pratica.', action: 'Prova con il mio corso', step: 'Passo', titles: ['Carica il corso', 'Cogli l’essenziale', 'Passa alla pratica'] },
    moments: { eyebrow: 'Dentro CramDesk', first: 'Quattro momenti per', accent: 'imparare meglio.', description: 'Ogni strumento segue lo stesso corso e ti aiuta a capire, ricordare o riprendere un argomento.', labels: ['Capire.', 'Memorizzare.', 'Metterti alla prova.', 'Approfondire.'], descriptions: ['Un riassunto e una spiegazione più semplice chiariscono le idee prima di memorizzarle.', 'Le schede domanda-risposta allenano il richiamo attivo al tuo ritmo.', 'I quiz creati dal documento mostrano quali passaggi ripassare.', 'Fai una domanda sul corso e ricevi una risposta basata sul testo estratto.'], sampleLabels: ['Idea chiave', 'Domanda 01', 'Tocca a te', 'Nella chat'], samples: ['Una membrana flessibile regola gli scambi tra la cellula e l’ambiente.', 'Qual è la funzione della membrana cellulare?', 'Scegli una risposta e scopri cosa ripassare.', '«Puoi spiegarmi il doppio strato in modo semplice?»'] },
    tools: { eyebrow: 'Strumenti gratuiti · Senza account', first: 'Prepara il tuo PDF.', accent: 'Poi studialo.', description: 'Unisci, estrai o riordina le pagine nel browser prima del ripasso. I file restano sul tuo dispositivo.', action: 'Apri gli strumenti PDF gratuiti', textTitle: 'Cerchi un concetto?', textDescription: 'Esamina le pagine, cerca nel testo e scaricalo sul dispositivo.', textAction: 'Esplora il testo del PDF', organizeTitle: 'Le pagine sono in disordine?', organizeDescription: 'Spostale visivamente e scarica il nuovo PDF.', organizeAction: 'Riordina il PDF', note: 'Senza registrazione né carta. Questi strumenti funzionano nel browser.', example: 'Esempio di percorso', thisWeek: 'Prima di studiare', tasks: ['Prepara le pagine', 'Trova il passaggio chiave', 'Esercitati con il corso'], progress: 'Tutto pronto per una sessione di studio.' },
    pricing: { eyebrow: 'Prezzi chiari', first: 'Uno spazio per', accent: 'ogni ritmo di studio.', description: 'Inizia con 7 giorni di prova senza carta. Poi scegli il volume più adatto a te.' },
    faq: { first: 'Prima di', accent: 'iniziare.', cancelQuestion: 'Posso annullare l’abbonamento?', cancelAnswer: 'Sì. Puoi gestire o annullare l’abbonamento dalla sezione pagamenti.' },
    cta: { first: 'Il tuo corso può diventare', accent: 'il tuo miglior ripasso.', description: 'Prova CramDesk per sette giorni senza carta.', action: 'Carica il mio PDF' },
    footer: { description: 'Uno spazio più chiaro per capire il corso ed esercitarti al tuo ritmo.', explore: 'Esplora', studio: 'Spazio di studio', tools: 'Strumenti PDF gratuiti', inspect: 'Esplora un PDF', pricing: 'Prezzi', privacy: 'Privacy', terms: 'Condizioni', contact: 'Contatti' },
  },
  pt: {
    hero: { lead: 'O teu PDF de estudo,', accent: 'pronto para rever.', upload: 'Começa com o teu PDF', note: '7 dias de teste sem cartão · PDF com texto selecionável', how: 'Vê como funciona' },
    studio: { file: 'Biologia celular.pdf', ready: 'Documento pronto para rever', demo: 'Demonstração interativa', workspace: 'O meu espaço', documents: 'Documentos', study: 'Rever', cards: 'Cartões', chapter: 'Capítulo 04 · Ciências', topic: 'A membrana celular', tabs: ['Resumo', 'Cartões', 'Questionário'], summaryLabel: 'O essencial, com clareza', summary: 'A membrana celular separa a célula do meio envolvente e regula as trocas. A sua estrutura flexível é uma bicamada de fosfolípidos.', keyIdeas: ['Uma barreira seletiva protege o interior da célula.', 'As proteínas da membrana ajudam certas moléculas a atravessá-la.'], sourceLabel: 'Excerto de demonstração', source: 'A membrana plasmática é formada por uma bicamada de fosfolípidos. Separa o interior da célula do meio exterior e participa nas trocas.', sourceNote: 'O resumo continua ligado ao texto do curso para poderes confirmar cada ideia.', cardLabel: 'Recordação ativa · Cartão 01', cardQuestion: 'Qual é a função principal da membrana celular?', cardAnswer: 'Controla as trocas entre a célula e o meio envolvente.', reveal: 'Mostrar resposta', hide: 'Mostrar pergunta', quizLabel: 'Testa o que recordas · Pergunta 01', quizQuestion: 'Que estrutura forma a barreira da membrana?', quizAnswers: ['Uma bicamada de fosfolípidos', 'Uma única camada de proteínas', 'Uma parede de celulose'], correct: 'Certo. A bicamada é a base dessa barreira.', incorrect: 'Ainda não. Revê o trecho sobre a bicamada de fosfolípidos.' },
    overview: { eyebrow: 'Um espaço para compreender e rever', title: 'Depois de enviar, está tudo no mesmo lugar.', description: 'Consulta o resumo, faz perguntas sobre o documento e testa a tua compreensão ao teu ritmo.', trust: ['Resumos, cartões e questionários juntos', 'Interface em nove idiomas', 'Documentos disponíveis na tua conta'] },
    method: { eyebrow: 'Outra forma de estudar', first: 'Ler é bom.', accent: 'Recordar', last: 'é melhor.', description: 'Quando os materiais se acumulam, um resumo claro e perguntas específicas ajudam a passar da leitura à prática.', action: 'Experimentar com o meu curso', step: 'Passo', titles: ['Envia o teu curso', 'Vê o essencial', 'Passa à prática'] },
    moments: { eyebrow: 'No CramDesk', first: 'Quatro momentos para', accent: 'aprender melhor.', description: 'Cada ferramenta acompanha o mesmo curso e ajuda-te a compreender, memorizar ou voltar ao que falta.', labels: ['Compreender.', 'Memorizar.', 'Testar-te.', 'Aprofundar.'], descriptions: ['Um resumo e uma explicação mais simples esclarecem as ideias antes de as memorizar.', 'Os cartões de pergunta e resposta treinam a recordação ativa ao teu ritmo.', 'Os questionários criados a partir do documento mostram o que precisas de rever.', 'Faz uma pergunta sobre o curso e recebe uma resposta baseada no texto extraído.'], sampleLabels: ['Ideia-chave', 'Pergunta 01', 'A tua vez', 'No chat'], samples: ['Uma membrana flexível regula as trocas entre a célula e o meio envolvente.', 'Qual é a função da membrana celular?', 'Escolhe uma resposta e vê o que deves rever.', '«Podes explicar a bicamada de forma simples?»'] },
    tools: { eyebrow: 'Ferramentas grátis · Sem conta', first: 'Prepara o teu PDF.', accent: 'Depois estuda-o.', description: 'Junta, extrai ou reorganiza páginas no navegador antes de rever. Os ficheiros ficam no teu dispositivo.', action: 'Abrir ferramentas PDF grátis', textTitle: 'Precisas de encontrar um conceito?', textDescription: 'Consulta as páginas, pesquisa o texto e descarrega-o localmente.', textAction: 'Explorar o texto do PDF', organizeTitle: 'Páginas fora de ordem?', organizeDescription: 'Move-as visualmente e descarrega o novo PDF.', organizeAction: 'Organizar o meu PDF', note: 'Sem registo nem cartão. As ferramentas funcionam no teu navegador.', example: 'Exemplo de percurso', thisWeek: 'Antes de estudar', tasks: ['Preparar as páginas', 'Encontrar a passagem importante', 'Praticar com o curso'], progress: 'Pronto para uma sessão de estudo focada.' },
    pricing: { eyebrow: 'Preços claros', first: 'Um espaço para', accent: 'cada ritmo de estudo.', description: 'Começa com 7 dias de teste sem cartão. Depois escolhe o volume adequado.' },
    faq: { first: 'Antes de', accent: 'começar.', cancelQuestion: 'Posso cancelar a subscrição?', cancelAnswer: 'Sim. Podes gerir ou cancelar a subscrição na área de faturação.' },
    cta: { first: 'O teu curso pode tornar-se', accent: 'a tua melhor revisão.', description: 'Experimenta o CramDesk durante sete dias sem cartão.', action: 'Enviar o meu PDF' },
    footer: { description: 'Um espaço mais claro para compreender o curso e praticar ao teu ritmo.', explore: 'Explorar', studio: 'Área de estudo', tools: 'Ferramentas PDF grátis', inspect: 'Explorar um PDF', pricing: 'Preços', privacy: 'Privacidade', terms: 'Condições', contact: 'Contacto' },
  },
  zh: {
    hero: { lead: '你的课程 PDF，', accent: '即刻开始复习。', upload: '从 PDF 开始', note: '免费试用 7 天，无需银行卡 · PDF 须含可选中文字', how: '了解使用方法' },
    studio: { file: '细胞生物学.pdf', ready: '文档已准备好复习', demo: '交互演示', workspace: '我的空间', documents: '文档', study: '复习', cards: '卡片', chapter: '第 04 章 · 科学', topic: '细胞膜', tabs: ['摘要', '记忆卡', '测验'], summaryLabel: '清楚掌握核心内容', summary: '细胞膜将细胞与周围环境分开，并调节物质交换。它的柔性结构由磷脂双分子层构成。', keyIdeas: ['选择性屏障保护细胞内部。', '膜蛋白帮助某些分子穿过细胞膜。'], sourceLabel: '演示原文片段', source: '细胞膜由磷脂双分子层构成。它将细胞内部与外部环境分开，并参与物质交换。', sourceNote: '摘要与课程原文保持关联，方便逐条核对。', cardLabel: '主动回忆 · 卡片 01', cardQuestion: '细胞膜的主要作用是什么？', cardAnswer: '调节细胞与周围环境之间的物质交换。', reveal: '查看答案', hide: '返回问题', quizLabel: '检验记忆 · 问题 01', quizQuestion: '细胞膜的屏障由什么结构构成？', quizAnswers: ['磷脂双分子层', '单层蛋白质', '纤维素细胞壁'], correct: '正确。磷脂双分子层是这道屏障的基础。', incorrect: '还不对。再读一遍磷脂双分子层的相关段落。' },
    overview: { eyebrow: '在一个空间里理解与复习', title: '上传之后，学习内容都在一起。', description: '阅读摘要、向文档提问，并按自己的节奏检验理解。', trust: ['笔记、卡片和测验集中管理', '支持九种界面语言', '登录后可查看自己的文档'] },
    method: { eyebrow: '换一种学习方式', first: '阅读很重要，', accent: '记住内容', last: '更重要。', description: '课程资料越积越多时，清晰的摘要和有针对性的问题能帮助你从阅读转向练习。', action: '用我的课程试一试', step: '步骤', titles: ['上传课程资料', '抓住核心内容', '开始练习'] },
    moments: { eyebrow: 'CramDesk 学习流程', first: '四个环节，', accent: '学得更扎实。', description: '所有工具围绕同一份课程资料，帮助你明确需要理解、记忆或重温的内容。', labels: ['理解。', '记忆。', '检验。', '深入。'], descriptions: ['先用摘要和更易懂的解释掌握概念，再开始记忆。', '用问答卡片按自己的节奏练习主动回忆。', '根据文档生成的测验帮你找到需要重温的段落。', '就课程提问，获得基于提取文本的回答。'], sampleLabels: ['核心观点', '问题 01', '轮到你了', '在聊天中'], samples: ['柔性的细胞膜调节细胞与环境之间的物质交换。', '细胞膜的作用是什么？', '选择答案，看看哪些内容还要复习。', '“能简单解释一下磷脂双分子层吗？”'] },
    tools: { eyebrow: '免费工具 · 无需注册', first: '先整理 PDF，', accent: '再专心复习。', description: '在浏览器中合并、提取或重新排列页面。文件始终留在你的设备上。', action: '打开免费 PDF 工具', textTitle: '想找到某个概念？', textDescription: '查看页面、搜索文字，并在本地下载提取内容。', textAction: '查看 PDF 文字', organizeTitle: '页面顺序需要调整？', organizeDescription: '直观地移动页面并下载新的 PDF。', organizeAction: '整理 PDF', note: '无需注册或银行卡，免费工具直接在浏览器中运行。', example: '示例流程', thisWeek: '复习之前', tasks: ['整理页面', '找到关键段落', '用课程内容练习'], progress: '现在可以开始专注复习。' },
    pricing: { eyebrow: '价格清晰', first: '找到适合自己', accent: '学习节奏的空间。', description: '无需银行卡即可试用 7 天，之后按需要选择套餐。' },
    faq: { first: '开始之前，', accent: '先了解这些。', cancelQuestion: '可以取消订阅吗？', cancelAnswer: '可以。你可以在账单页面管理或取消订阅。' },
    cta: { first: '让课程资料成为', accent: '更有效的复习练习。', description: '无需银行卡，免费试用 CramDesk 七天。', action: '上传我的 PDF' },
    footer: { description: '用更清晰的方式理解课程，并按自己的节奏练习。', explore: '探索', studio: '学习空间', tools: '免费 PDF 工具', inspect: '查看 PDF', pricing: '价格', privacy: '隐私', terms: '条款', contact: '联系' },
  },
  ja: {
    hero: { lead: '授業のPDFを、', accent: '復習しやすい形に。', upload: 'PDFから始める', note: 'カード不要で7日間お試し · 文字を選択できるPDF', how: '使い方を見る' },
    studio: { file: '細胞生物学.pdf', ready: '復習できる状態です', demo: '操作できるデモ', workspace: 'マイスペース', documents: '資料', study: '復習', cards: 'カード', chapter: '第04章 · 理科', topic: '細胞膜', tabs: ['要約', 'カード', 'クイズ'], summaryLabel: '要点をわかりやすく', summary: '細胞膜は細胞を周囲の環境から隔て、物質の出入りを調節します。柔軟な構造はリン脂質二重層でできています。', keyIdeas: ['選択的な障壁が細胞の内部を守ります。', '膜タンパク質は特定の分子の通過を助けます。'], sourceLabel: 'デモ用の原文', source: '細胞膜はリン脂質二重層からなります。細胞の内部を外部環境から隔て、物質のやり取りに関わります。', sourceNote: '要約を元の教材と結び付け、各ポイントを確認できます。', cardLabel: '能動的想起 · カード01', cardQuestion: '細胞膜の主な役割は何ですか？', cardAnswer: '細胞と周囲の環境との物質のやり取りを調節します。', reveal: '答えを見る', hide: '問題に戻る', quizLabel: '理解度チェック · 問題01', quizQuestion: '細胞膜の障壁を作る構造は何ですか？', quizAnswers: ['リン脂質二重層', '単層のタンパク質', 'セルロースの壁'], correct: '正解です。二重層がこの障壁の土台です。', incorrect: 'もう一度、リン脂質二重層の説明を確認しましょう。' },
    overview: { eyebrow: '理解も復習も一つの場所で', title: 'アップロード後は、すべてここに。', description: '要約を読み、資料に質問し、自分のペースで理解度を確かめられます。', trust: ['ノート・カード・クイズを一か所に', '9言語に対応した画面', 'アカウントから資料にアクセス'] },
    method: { eyebrow: '新しい学び方', first: '読むことから、', accent: '思い出せる', last: 'ことへ。', description: '教材が増えても、明快な要約と的を絞った質問があれば、読むだけでなく実際に練習できます。', action: '自分の教材で試す', step: 'ステップ', titles: ['教材をアップロード', '要点をつかむ', '実際に練習する'] },
    moments: { eyebrow: 'CramDeskの中で', first: '学びを深める', accent: '四つの場面。', description: 'すべてのツールが同じ教材に沿って、理解・記憶・復習を支えます。', labels: ['理解する。', '覚える。', '試す。', '深める。'], descriptions: ['要約とやさしい解説で、暗記の前に重要な考え方を理解します。', '質問と回答のカードで、自分のペースで能動的に思い出します。', '資料から作るクイズで、もう一度読むべき箇所が見つかります。', '教材について質問し、抽出した文章に基づく回答を受け取れます。'], sampleLabels: ['重要な考え', '問題01', 'やってみよう', 'チャットでは'], samples: ['柔軟な細胞膜は細胞と環境との物質交換を調節します。', '細胞膜にはどんな役割がありますか？', '答えを選び、復習するポイントを確認。', '「二重層を簡単に説明してくれる？」'] },
    tools: { eyebrow: '無料ツール · 登録不要', first: 'PDFを整えて、', accent: '学習を始めよう。', description: 'ブラウザー内でページを結合・抽出・並べ替え。ファイルは端末から送信されません。', action: '無料PDFツールを開く', textTitle: '用語を探したい？', textDescription: 'ページを確認し、文章を検索して端末に保存できます。', textAction: 'PDFの文章を見る', organizeTitle: 'ページの順番が違う？', organizeDescription: '画面上で移動して、新しいPDFをダウンロードできます。', organizeAction: 'PDFを並べ替える', note: '登録もカードも不要。無料ツールはブラウザー内で動きます。', example: '利用例', thisWeek: '学習を始める前に', tasks: ['ページを整理', '重要な箇所を探す', '教材を使って練習'], progress: '集中して復習する準備ができました。' },
    pricing: { eyebrow: 'わかりやすい料金', first: '学習のペースに合う', accent: 'プランを選ぼう。', description: 'カード登録なしで7日間試し、その後に必要な利用量を選べます。' },
    faq: { first: '始める前に', accent: '確認しよう。', cancelQuestion: 'サブスクリプションを解約できますか？', cancelAnswer: 'はい。請求ページから管理・解約できます。' },
    cta: { first: '授業の資料を、', accent: '自分に合う復習へ。', description: 'カード不要でCramDeskを7日間お試しください。', action: 'PDFをアップロード' },
    footer: { description: '授業を理解し、自分のペースで練習できる、わかりやすい学習スペース。', explore: '見る', studio: '学習スペース', tools: '無料PDFツール', inspect: 'PDFを調べる', pricing: '料金', privacy: 'プライバシー', terms: '利用規約', contact: 'お問い合わせ' },
  },
  ar: {
    hero: { lead: 'ملف مقررك الدراسي،', accent: 'جاهز للمراجعة.', upload: 'ابدأ بملف PDF', note: 'تجربة 7 أيام دون بطاقة دفع · ملف PDF بنص قابل للتحديد', how: 'تعرّف على طريقة العمل' },
    studio: { file: 'الأحياء الخلوية.pdf', ready: 'المستند جاهز للمراجعة', demo: 'عرض تفاعلي توضيحي', workspace: 'مساحتي', documents: 'المستندات', study: 'المراجعة', cards: 'البطاقات', chapter: 'الفصل 04 · العلوم', topic: 'غشاء الخلية', tabs: ['الملخص', 'البطاقات', 'الاختبار'], summaryLabel: 'أهم الأفكار بوضوح', summary: 'يفصل غشاء الخلية بين الخلية ومحيطها وينظم تبادل المواد. وتتكون بنيته المرنة من طبقتين من الدهون الفسفورية.', keyIdeas: ['يحمي حاجز انتقائي داخل الخلية.', 'تساعد بروتينات الغشاء بعض الجزيئات على العبور.'], sourceLabel: 'مقتطف توضيحي من المصدر', source: 'يتكون الغشاء البلازمي من طبقتين من الدهون الفسفورية. ويفصل داخل الخلية عن الوسط الخارجي ويساهم في تبادل المواد.', sourceNote: 'يبقى الملخص مرتبطًا بنص الدرس لتتمكن من التحقق من كل فكرة.', cardLabel: 'استرجاع نشط · البطاقة 01', cardQuestion: 'ما الوظيفة الأساسية لغشاء الخلية؟', cardAnswer: 'ينظم تبادل المواد بين الخلية ومحيطها.', reveal: 'أظهر الإجابة', hide: 'أظهر السؤال', quizLabel: 'اختبر ما تتذكره · السؤال 01', quizQuestion: 'ما البنية التي تشكل حاجز الغشاء؟', quizAnswers: ['طبقتان من الدهون الفسفورية', 'طبقة واحدة من البروتينات', 'جدار من السليلوز'], correct: 'صحيح. تشكل الطبقتان أساس هذا الحاجز.', incorrect: 'ليس تمامًا. راجع الفقرة المتعلقة بطبقتي الدهون الفسفورية.' },
    overview: { eyebrow: 'مساحة واحدة للفهم والمراجعة', title: 'بعد الرفع، كل شيء في مكان واحد.', description: 'اقرأ الملخص، واسأل عن مستندك، واختبر فهمك بالوتيرة التي تناسبك.', trust: ['ملخصات وبطاقات واختبارات في مكان واحد', 'واجهة بتسع لغات', 'مستنداتك متاحة من حسابك'] },
    method: { eyebrow: 'طريقة أخرى للدراسة', first: 'القراءة مفيدة،', accent: 'والتذكر', last: 'أفضل.', description: 'عندما تتراكم الدروس، يساعدك ملخص واضح وأسئلة محددة على الانتقال من القراءة إلى التطبيق.', action: 'جرّب باستخدام درسي', step: 'الخطوة', titles: ['ارفع مقررك', 'اطّلع على الأفكار الأساسية', 'انتقل إلى التطبيق'] },
    moments: { eyebrow: 'داخل CramDesk', first: 'أربع مراحل من أجل', accent: 'تعلم أفضل.', description: 'تتبع جميع الأدوات المقرر نفسه وتساعدك على تحديد ما ينبغي فهمه أو تذكره أو مراجعته.', labels: ['افهم.', 'احفظ.', 'اختبر نفسك.', 'تعمّق.'], descriptions: ['يساعدك الملخص والشرح الأبسط على استيعاب الأفكار قبل حفظها.', 'تدربك بطاقات السؤال والجواب على الاسترجاع النشط وفق وتيرتك.', 'تكشف الاختبارات المستندة إلى ملفك الأجزاء التي تستحق المراجعة.', 'اطرح سؤالًا عن المقرر واحصل على إجابة تستند إلى النص المستخرج.'], sampleLabels: ['الفكرة الأساسية', 'السؤال 01', 'دورك الآن', 'في المحادثة'], samples: ['ينظم غشاء مرن تبادل المواد بين الخلية ومحيطها.', 'ما وظيفة غشاء الخلية؟', 'اختر إجابة واعرف ما يحتاج إلى مراجعة.', '«هل يمكنك شرح الطبقتين ببساطة؟»'] },
    tools: { eyebrow: 'أدوات مجانية · دون حساب', first: 'جهّز ملف PDF،', accent: 'ثم ابدأ المراجعة.', description: 'ادمج الصفحات أو استخرجها أو أعد ترتيبها داخل المتصفح. تبقى ملفاتك على جهازك.', action: 'افتح أدوات PDF المجانية', textTitle: 'تبحث عن مفهوم معين؟', textDescription: 'افحص الصفحات وابحث في النص ونزّله على جهازك.', textAction: 'استكشف نص PDF', organizeTitle: 'هل ترتيب الصفحات غير مناسب؟', organizeDescription: 'حرّكها بصريًا ونزّل ملف PDF الجديد.', organizeAction: 'رتّب ملف PDF', note: 'دون تسجيل أو بطاقة دفع. تعمل الأدوات المجانية داخل المتصفح.', example: 'مثال لسير العمل', thisWeek: 'قبل المراجعة', tasks: ['جهّز الصفحات', 'اعثر على الفقرة المهمة', 'تدرب باستخدام المقرر'], progress: 'أصبحت جاهزًا لجلسة مراجعة مركزة.' },
    pricing: { eyebrow: 'أسعار واضحة', first: 'مساحة تناسب', accent: 'وتيرة دراستك.', description: 'ابدأ بتجربة لمدة 7 أيام دون بطاقة دفع، ثم اختر الحجم المناسب لك.' },
    faq: { first: 'قبل أن', accent: 'تبدأ.', cancelQuestion: 'هل يمكنني إلغاء اشتراكي؟', cancelAnswer: 'نعم. يمكنك إدارة اشتراكك أو إلغاؤه من قسم الفوترة.' },
    cta: { first: 'يمكن أن يصبح مقررك', accent: 'أفضل جلسة مراجعة لك.', description: 'جرّب CramDesk سبعة أيام دون بطاقة دفع.', action: 'ارفع ملف PDF الخاص بي' },
    footer: { description: 'مساحة أوضح لفهم مقررك والتدرب بالوتيرة التي تناسبك.', explore: 'استكشف', studio: 'مساحة الدراسة', tools: 'أدوات PDF مجانية', inspect: 'استكشف PDF', pricing: 'الأسعار', privacy: 'الخصوصية', terms: 'الشروط', contact: 'تواصل معنا' },
  },
}
