import type { PdfTool } from '@/lib/pdf-tools'

type Copy = {
  slug: string
  name: string
  title: string
  description: string
  intro: string
  steps: [string, string, string]
  uses: [string, string]
  tip: string
  question: string
  answer: string
}

export type PdfToolPage = { id: PdfTool; fr: Copy; en: Copy }

export const pdfToolPages: PdfToolPage[] = [
  { id: 'merge', fr: { slug: 'fusionner-pdf', name: 'Fusionner des PDF', title: 'Fusionner des PDF gratuitement en ligne', description: 'Assemble plusieurs PDF dans l’ordre voulu. Prévisualise les fichiers, change leur ordre et télécharge le résultat. Gratuit et sans envoi sur un serveur.', intro: 'Regroupe des chapitres, polycopiés ou annexes en un seul document. Ajoute au moins deux PDF, vérifie leur ordre, puis récupère le fichier assemblé.', steps: ['Ajoute au moins deux fichiers PDF.', 'Déplace les fichiers pour choisir leur ordre.', 'Lance la fusion et télécharge le PDF obtenu.'], uses: ['Rassembler les cours d’un semestre.', 'Joindre un sujet et son corrigé.'], tip: 'L’ordre des fichiers détermine l’ordre des pages dans le document final.', question: 'Puis-je fusionner un PDF protégé par mot de passe ?', answer: 'Non. Déverrouille le document avec l’autorisation nécessaire avant de l’ajouter.' }, en: { slug: 'merge-pdf', name: 'Merge PDFs', title: 'Merge PDF files online for free', description: 'Combine PDFs in your chosen order. Preview and reorder files, then download the result. Free and processed on your device.', intro: 'Put chapters, lecture notes or appendices into one document. Add at least two PDFs, check their order and download the combined file.', steps: ['Add at least two PDF files.', 'Move files to set the right order.', 'Merge and download your PDF.'], uses: ['Combine a semester of course notes.', 'Keep an assignment with its answer key.'], tip: 'File order determines page order in the finished document.', question: 'Can I merge a password-protected PDF?', answer: 'No. Unlock it with the necessary permission before adding it.' } },
  { id: 'extract', fr: { slug: 'extraire-pages-pdf', name: 'Extraire des pages', title: 'Extraire des pages d’un PDF gratuitement', description: 'Sélectionne visuellement les pages à conserver et crée un nouveau PDF. Extraction gratuite dans le navigateur, sans compte ni transfert.', intro: 'Ne garde que le chapitre, les exercices ou les annexes dont tu as besoin. Les miniatures te permettent de choisir les pages sans deviner leur numéro.', steps: ['Ajoute un PDF avec du texte ou des images.', 'Clique sur les pages à conserver dans l’aperçu.', 'Télécharge le nouveau PDF contenant ta sélection.'], uses: ['Partager seulement un chapitre utile.', 'Isoler les pages d’exercices d’un polycopié.'], tip: 'La sélection conserve l’ordre original des pages. Pour changer cet ordre, utilise l’outil Réorganiser.', question: 'Le PDF d’origine est-il modifié ?', answer: 'Non. Un nouveau fichier est généré et ton document d’origine reste intact.' }, en: { slug: 'extract-pdf-pages', name: 'Extract PDF pages', title: 'Extract pages from a PDF for free', description: 'Visually select the pages you need and make a new PDF. Free browser-based extraction with no account or upload.', intro: 'Keep only the chapter, exercises or appendix you need. Page thumbnails make selection easier than guessing page numbers.', steps: ['Add a PDF file.', 'Click the pages you want to keep in the preview.', 'Download a new PDF with your selection.'], uses: ['Share only a relevant chapter.', 'Separate exercises from lecture notes.'], tip: 'Selected pages keep their original order. Use Reorder to change it.', question: 'Will my original PDF change?', answer: 'No. The tool creates a new file; your original remains untouched.' } },
  { id: 'organize', fr: { slug: 'reorganiser-pages-pdf', name: 'Réorganiser les pages', title: 'Réorganiser les pages d’un PDF en ligne', description: 'Déplace, retire et remets en ordre les pages de ton PDF grâce aux miniatures. Outil gratuit, local et sans inscription.', intro: 'Remets un cours dans le bon ordre ou retire des pages inutiles. L’aperçu visuel montre ce que tu conserves avant de créer le nouveau fichier.', steps: ['Charge ton PDF pour afficher ses pages.', 'Déplace les miniatures et retire les pages inutiles.', 'Crée le PDF dans le nouvel ordre.'], uses: ['Corriger l’ordre d’un scan de cours.', 'Retirer des pages blanches avant un partage.'], tip: 'Les pages retirées le sont uniquement dans le nouveau fichier téléchargé.', question: 'Puis-je réorganiser plusieurs PDF en une seule fois ?', answer: 'Cet outil réorganise un PDF à la fois. Fusionne d’abord tes fichiers si nécessaire.' }, en: { slug: 'reorder-pdf-pages', name: 'Reorder PDF pages', title: 'Reorder PDF pages online for free', description: 'Move and remove PDF pages using visual thumbnails. Free, on-device and no sign-up required.', intro: 'Fix the order of your notes or remove pages you do not need. Preview the result before creating a new file.', steps: ['Load a PDF to see its pages.', 'Move thumbnails and remove unwanted pages.', 'Create a PDF in the new order.'], uses: ['Fix pages in scanned notes.', 'Remove blank pages before sharing.'], tip: 'Removed pages are omitted only from the newly downloaded file.', question: 'Can I reorder several PDFs together?', answer: 'This tool works with one PDF at a time. Merge the files first if needed.' } },
  { id: 'rotate', fr: { slug: 'tourner-pages-pdf', name: 'Tourner des pages', title: 'Tourner les pages d’un PDF gratuitement', description: 'Redresse une page ou tout un PDF à 90°, 180° ou 270°. Choisis les pages dans l’aperçu et télécharge le document corrigé.', intro: 'Un scan à l’envers ou une page de travers ? Sélectionne les pages concernées et applique la même rotation en quelques clics.', steps: ['Ajoute le PDF et visualise ses pages.', 'Choisis les pages à tourner et l’angle.', 'Télécharge le PDF redressé.'], uses: ['Corriger un scan photographié de côté.', 'Remettre une annexe dans le bon sens.'], tip: 'La rotation s’ajoute à l’orientation actuelle de chaque page.', question: 'Puis-je tourner seulement certaines pages ?', answer: 'Oui. Sélectionne les pages voulues dans l’aperçu avant de lancer la rotation.' }, en: { slug: 'rotate-pdf', name: 'Rotate PDF pages', title: 'Rotate PDF pages online for free', description: 'Rotate selected pages or an entire PDF by 90°, 180° or 270°. Preview pages and download the corrected document.', intro: 'Got a sideways scan or upside-down page? Select the affected pages and apply the rotation in a few clicks.', steps: ['Add a PDF and preview its pages.', 'Select pages and choose an angle.', 'Download the corrected PDF.'], uses: ['Fix a sideways scan.', 'Turn an appendix the right way up.'], tip: 'Rotation is added to each page’s current orientation.', question: 'Can I rotate only some pages?', answer: 'Yes. Select the pages you want in the preview before processing.' } },
  { id: 'number', fr: { slug: 'numeroter-pages-pdf', name: 'Numéroter les pages', title: 'Numéroter les pages d’un PDF gratuitement', description: 'Ajoute des numéros discrets en bas des pages de ton PDF. Gratuit, sans compte et traité directement dans ton navigateur.', intro: 'Facilite la lecture et les références dans un cours, un dossier ou un support distribué. Chaque page reçoit son numéro dans un nouveau PDF.', steps: ['Importe le PDF à numéroter.', 'Vérifie l’aperçu et l’ordre des pages.', 'Télécharge la version paginée.'], uses: ['Retrouver une notion pendant une révision en groupe.', 'Référencer une page précise dans un dossier.'], tip: 'Les numéros commencent à 1 et sont centrés en bas de chaque page. Si le document est déjà numéroté, vérifie le résultat.', question: 'Puis-je choisir un autre emplacement ou numéro de départ ?', answer: 'Pas encore. La numérotation actuelle commence à 1 et s’affiche au centre du bas de page.' }, en: { slug: 'add-page-numbers-to-pdf', name: 'Add page numbers', title: 'Add page numbers to a PDF for free', description: 'Add discreet numbers to the bottom of PDF pages. Free, no account and processed entirely in your browser.', intro: 'Make course notes or shared documents easier to reference. Each page gets its number in a new PDF.', steps: ['Import the PDF to number.', 'Check the preview and page order.', 'Download the numbered version.'], uses: ['Find a concept during group study.', 'Refer to a specific page in a handout.'], tip: 'Numbers start at 1 and appear centered at the bottom. Check the result if your PDF already has numbers.', question: 'Can I set a different position or starting number?', answer: 'Not yet. Numbers currently start at 1 and appear at the bottom center.' } },
  { id: 'watermark', fr: { slug: 'ajouter-filigrane-pdf', name: 'Ajouter un filigrane', title: 'Ajouter un filigrane à un PDF gratuitement', description: 'Ajoute un texte en filigrane sur toutes les pages de ton PDF. Personnalise le texte et télécharge le résultat sans compte.', intro: 'Marque une version de travail ou un document à relire avec un texte léger placé au centre de chaque page.', steps: ['Charge ton PDF.', 'Écris un texte court pour le filigrane.', 'Crée et télécharge le PDF marqué.'], uses: ['Signaler un brouillon de cours.', 'Identifier une copie de travail.'], tip: 'Le texte du filigrane accepte actuellement les caractères latins simples et 60 caractères au maximum.', question: 'Le filigrane protège-t-il le PDF contre la copie ?', answer: 'Non. Il s’agit d’un repère visuel, pas d’une protection contre la copie ou la modification.' }, en: { slug: 'watermark-pdf', name: 'Watermark PDF', title: 'Add a watermark to a PDF for free', description: 'Place a text watermark on every PDF page. Set the text and download the result without an account.', intro: 'Mark a draft or review copy with light text centered on each page.', steps: ['Load your PDF.', 'Enter short watermark text.', 'Create and download the marked PDF.'], uses: ['Label draft lecture notes.', 'Identify a working copy.'], tip: 'Watermark text currently supports simple Latin characters and up to 60 characters.', question: 'Does a watermark prevent copying?', answer: 'No. It is a visual label, not copy or edit protection.' } },
  { id: 'metadata', fr: { slug: 'effacer-metadonnees-pdf', name: 'Effacer les métadonnées', title: 'Effacer les métadonnées d’un PDF gratuitement', description: 'Retire les champs standards de titre, auteur, sujet et logiciel d’un PDF. Traitement local et gratuit, sans upload.', intro: 'Nettoie les champs de métadonnées standards avant de partager un PDF. Contrôle toujours le contenu visible et les éventuelles données intégrées séparément.', steps: ['Ajoute le PDF à nettoyer.', 'Lance l’effacement des champs standards.', 'Télécharge et vérifie le nouveau fichier.'], uses: ['Retirer un nom d’auteur dans les propriétés du fichier.', 'Supprimer un titre ou un logiciel de création obsolète.'], tip: 'Cet outil ne garantit pas l’anonymisation : annotations, contenu visible et autres données intégrées peuvent rester.', question: 'Les noms présents dans les pages sont-ils supprimés ?', answer: 'Non. Seuls les champs de métadonnées standards sont effacés. Relis le PDF avant de le partager.' }, en: { slug: 'remove-pdf-metadata', name: 'Remove PDF metadata', title: 'Remove standard PDF metadata for free', description: 'Clear standard title, author, subject and software fields from a PDF. Free on-device processing with no upload.', intro: 'Clear standard metadata fields before sharing a PDF. Always inspect visible content and other embedded information separately.', steps: ['Add the PDF you want to clean.', 'Clear the standard metadata fields.', 'Download and inspect the new file.'], uses: ['Remove an author name from file properties.', 'Clear an outdated title or creation tool.'], tip: 'This tool does not guarantee anonymity: annotations, visible content and other embedded data may remain.', question: 'Will names visible on pages be removed?', answer: 'No. Only standard metadata fields are cleared. Review the PDF before sharing.' } },
  { id: 'images', fr: { slug: 'images-en-pdf', name: 'Convertir des images en PDF', title: 'Convertir JPG et PNG en PDF gratuitement', description: 'Assemble des images JPG ou PNG dans un PDF A4. Prévisualise, réorganise puis télécharge le fichier sans compte ni transfert.', intro: 'Regroupe tes photos de tableau, schémas ou captures dans un seul PDF A4. Les images gardent leurs proportions sur chaque page.', steps: ['Ajoute des images JPG ou PNG.', 'Mets-les dans l’ordre voulu.', 'Crée et télécharge le PDF A4.'], uses: ['Regrouper des photos de notes de cours.', 'Partager plusieurs schémas dans un document.'], tip: 'Chaque image occupe une page A4. Le fichier final peut rester volumineux si les images sont très grandes.', question: 'Les images sont-elles recadrées ?', answer: 'Non. Elles sont redimensionnées pour tenir dans la page A4 sans changer leurs proportions.' }, en: { slug: 'images-to-pdf', name: 'Images to PDF', title: 'Convert JPG and PNG images to PDF for free', description: 'Combine JPG and PNG images into an A4 PDF. Preview, reorder and download without an account or upload.', intro: 'Put whiteboard photos, diagrams or screenshots into one A4 PDF. Images keep their original proportions on each page.', steps: ['Add JPG or PNG images.', 'Arrange them in the order you want.', 'Create and download the A4 PDF.'], uses: ['Combine photos of study notes.', 'Share diagrams in one document.'], tip: 'Each image uses one A4 page. Large images may make the finished PDF large too.', question: 'Will my images be cropped?', answer: 'No. They are scaled to fit the A4 page without changing their proportions.' } },
]

export function pdfToolPath(page: PdfToolPage, locale: 'fr' | 'en') {
  return locale === 'fr' ? `/outils-pdf/${page.fr.slug}` : `/en/pdf-tools/${page.en.slug}`
}

export function findPdfToolPage(slug: string, locale: 'fr' | 'en') {
  return pdfToolPages.find(page => page[locale].slug === slug)
}
