import type { StudyPdfLocale } from '@/lib/study-pdf-locales'

type Copy = {
  eyebrow: string
  homeTitle: string
  homeLead: string
  readyTitle: string
  readyLead: string
  startToday: string
  practiceAnyway: string
  resume: string
  courses: string
  courseSingular: string
  courseCount: string
  cardSingular: string
  practicedToday: string
  deckLead: string
  browse: string
  browseLead: string
  sessionTitle: string
  pause: string
  question: string
  thinkFirst: string
  showAnswer: string
  ratePrompt: string
  answerCount: string
  finishLead: string
  openCourse: string
  openPdf: string
  noCoursesTitle: string
  noCoursesLead: string
}

export const revisionSpaceCopy: Record<StudyPdfLocale, Copy> = {
  fr: { eyebrow: 'Atelier de révision', homeTitle: 'Votre séance commence ici.', homeLead: 'Les notions à revoir sont rassemblées et classées par priorité. Avancez une question à la fois.', readyTitle: 'Vous êtes à jour.', readyLead: 'Aucune carte n’est due pour le moment. Vous pouvez pratiquer librement ou ouvrir un cours.', startToday: 'Réviser maintenant', practiceAnyway: 'Pratiquer librement', resume: 'Reprendre ma séance', courses: 'Mes cours', courseSingular: 'cours', courseCount: 'cours', cardSingular: 'carte', practicedToday: 'Travaillées aujourd’hui', deckLead: 'Une séance courte, avec vos notions les plus urgentes en premier.', browse: 'Parcourir les questions', browseLead: 'Ouvrez une question pour consulter sa réponse et sa source.', sessionTitle: 'Séance de révision', pause: 'Mettre en pause', question: 'Question', thinkFirst: 'Cherchez la réponse avant de la révéler.', showAnswer: 'Révéler la réponse', ratePrompt: 'À quel point vous en souveniez-vous ?', answerCount: 'réponses évaluées', finishLead: 'Votre travail est enregistré. Les notions difficiles reviendront plus tôt.', openCourse: 'Ouvrir le cours', openPdf: 'Voir la page du PDF', noCoursesTitle: 'Votre espace attend son premier cours.', noCoursesLead: 'Ajoutez un PDF et créez des cartes pour démarrer une séance de révision.' },
  en: { eyebrow: 'Study space', homeTitle: 'Your study session starts here.', homeLead: 'Due topics are gathered and prioritized. Work through one question at a time.', readyTitle: 'You are up to date.', readyLead: 'No cards are due right now. You can practice freely or open a course.', startToday: 'Study now', practiceAnyway: 'Practice freely', resume: 'Resume my session', courses: 'My courses', courseSingular: 'course', courseCount: 'courses', cardSingular: 'card', practicedToday: 'Studied today', deckLead: 'A short session with your most urgent topics first.', browse: 'Browse questions', browseLead: 'Open a question to see its answer and source.', sessionTitle: 'Study session', pause: 'Pause session', question: 'Question', thinkFirst: 'Recall the answer before revealing it.', showAnswer: 'Reveal answer', ratePrompt: 'How well did you remember it?', answerCount: 'answers rated', finishLead: 'Your work is saved. Difficult topics will return sooner.', openCourse: 'Open course', openPdf: 'View PDF page', noCoursesTitle: 'Your study space is ready for its first course.', noCoursesLead: 'Add a PDF and create cards to start studying.' },
  es: { eyebrow: 'Espacio de estudio', homeTitle: 'Tu sesión empieza aquí.', homeLead: 'Los conceptos pendientes están reunidos y ordenados por prioridad. Avanza pregunta a pregunta.', readyTitle: 'Estás al día.', readyLead: 'No hay tarjetas pendientes. Puedes practicar libremente o abrir un curso.', startToday: 'Repasar ahora', practiceAnyway: 'Practicar libremente', resume: 'Reanudar mi sesión', courses: 'Mis cursos', courseSingular: 'curso', courseCount: 'cursos', cardSingular: 'tarjeta', practicedToday: 'Repasadas hoy', deckLead: 'Una sesión breve con los conceptos más urgentes primero.', browse: 'Explorar preguntas', browseLead: 'Abre una pregunta para ver su respuesta y fuente.', sessionTitle: 'Sesión de repaso', pause: 'Pausar sesión', question: 'Pregunta', thinkFirst: 'Recuerda la respuesta antes de mostrarla.', showAnswer: 'Mostrar respuesta', ratePrompt: '¿Qué tan bien la recordabas?', answerCount: 'respuestas evaluadas', finishLead: 'Tu trabajo está guardado. Los conceptos difíciles volverán antes.', openCourse: 'Abrir curso', openPdf: 'Ver página del PDF', noCoursesTitle: 'Tu espacio espera su primer curso.', noCoursesLead: 'Añade un PDF y crea tarjetas para empezar a repasar.' },
  de: { eyebrow: 'Lernbereich', homeTitle: 'Deine Lerneinheit beginnt hier.', homeLead: 'Fällige Themen sind nach Priorität geordnet. Arbeite eine Frage nach der anderen durch.', readyTitle: 'Du bist auf dem Laufenden.', readyLead: 'Derzeit sind keine Karten fällig. Du kannst frei üben oder einen Kurs öffnen.', startToday: 'Jetzt lernen', practiceAnyway: 'Frei üben', resume: 'Lerneinheit fortsetzen', courses: 'Meine Kurse', courseSingular: 'Kurs', courseCount: 'Kurse', cardSingular: 'Karte', practicedToday: 'Heute gelernt', deckLead: 'Eine kurze Einheit mit den dringendsten Themen zuerst.', browse: 'Fragen durchsehen', browseLead: 'Öffne eine Frage, um Antwort und Quelle zu sehen.', sessionTitle: 'Lerneinheit', pause: 'Einheit pausieren', question: 'Frage', thinkFirst: 'Erinnere dich an die Antwort, bevor du sie aufdeckst.', showAnswer: 'Antwort aufdecken', ratePrompt: 'Wie gut hast du dich erinnert?', answerCount: 'bewertete Antworten', finishLead: 'Dein Fortschritt ist gespeichert. Schwierige Themen kommen früher zurück.', openCourse: 'Kurs öffnen', openPdf: 'PDF-Seite ansehen', noCoursesTitle: 'Dein Lernbereich wartet auf den ersten Kurs.', noCoursesLead: 'Füge ein PDF hinzu und erstelle Karten, um loszulegen.' },
  it: { eyebrow: 'Spazio di studio', homeTitle: 'La tua sessione inizia qui.', homeLead: 'Gli argomenti da ripassare sono riuniti e ordinati per priorità. Procedi una domanda alla volta.', readyTitle: 'Sei in pari.', readyLead: 'Nessuna scheda da ripassare ora. Puoi esercitarti liberamente o aprire un corso.', startToday: 'Ripassa ora', practiceAnyway: 'Esercitati liberamente', resume: 'Riprendi la sessione', courses: 'I miei corsi', courseSingular: 'corso', courseCount: 'corsi', cardSingular: 'scheda', practicedToday: 'Studiate oggi', deckLead: 'Una breve sessione con gli argomenti più urgenti per primi.', browse: 'Sfoglia le domande', browseLead: 'Apri una domanda per vedere risposta e fonte.', sessionTitle: 'Sessione di ripasso', pause: 'Metti in pausa', question: 'Domanda', thinkFirst: 'Ricorda la risposta prima di mostrarla.', showAnswer: 'Mostra la risposta', ratePrompt: 'Quanto bene la ricordavi?', answerCount: 'risposte valutate', finishLead: 'Il tuo lavoro è salvato. Gli argomenti difficili torneranno prima.', openCourse: 'Apri il corso', openPdf: 'Vedi la pagina PDF', noCoursesTitle: 'Il tuo spazio attende il primo corso.', noCoursesLead: 'Aggiungi un PDF e crea schede per iniziare.' },
  pt: { eyebrow: 'Espaço de estudo', homeTitle: 'A tua sessão começa aqui.', homeLead: 'Os temas a rever estão reunidos e ordenados por prioridade. Avança uma pergunta de cada vez.', readyTitle: 'Estás em dia.', readyLead: 'Não há cartões pendentes. Podes praticar livremente ou abrir um curso.', startToday: 'Rever agora', practiceAnyway: 'Praticar livremente', resume: 'Retomar a sessão', courses: 'Os meus cursos', courseSingular: 'curso', courseCount: 'cursos', cardSingular: 'cartão', practicedToday: 'Revistos hoje', deckLead: 'Uma sessão curta com os temas mais urgentes primeiro.', browse: 'Explorar perguntas', browseLead: 'Abre uma pergunta para ver a resposta e a fonte.', sessionTitle: 'Sessão de revisão', pause: 'Pausar sessão', question: 'Pergunta', thinkFirst: 'Recorda a resposta antes de a revelar.', showAnswer: 'Revelar resposta', ratePrompt: 'Quão bem te lembravas?', answerCount: 'respostas avaliadas', finishLead: 'O teu trabalho está guardado. Os temas difíceis voltarão mais cedo.', openCourse: 'Abrir curso', openPdf: 'Ver página do PDF', noCoursesTitle: 'O teu espaço espera pelo primeiro curso.', noCoursesLead: 'Adiciona um PDF e cria cartões para começar a estudar.' },
  zh: { eyebrow: '复习空间', homeTitle: '从这里开始今天的复习。', homeLead: '待复习知识点已按优先级排列。一次专注一道题。', readyTitle: '目前已完成复习。', readyLead: '现在没有到期卡片。你仍可自由练习或打开课程。', startToday: '立即复习', practiceAnyway: '自由练习', resume: '继续本次复习', courses: '我的课程', courseSingular: '门课程', courseCount: '门课程', cardSingular: '张卡片', practicedToday: '今日已学习', deckLead: '先复习最需要巩固的知识点。', browse: '浏览问题', browseLead: '展开问题可查看答案和出处。', sessionTitle: '复习时段', pause: '暂停复习', question: '问题', thinkFirst: '先尝试回忆，再显示答案。', showAnswer: '显示答案', ratePrompt: '你记得有多清楚？', answerCount: '次回答已评分', finishLead: '学习记录已保存。难点会更早出现。', openCourse: '打开课程', openPdf: '查看 PDF 页面', noCoursesTitle: '添加第一门课程，开始复习。', noCoursesLead: '上传 PDF 并创建卡片，即可开始学习。' },
  ja: { eyebrow: '復習スペース', homeTitle: '今日の復習をここから。', homeLead: '復習が必要な項目を優先順にまとめました。一問ずつ集中して進めましょう。', readyTitle: '今の復習は完了です。', readyLead: '期限の来たカードはありません。自由に練習するか、教材を開けます。', startToday: '今すぐ復習', practiceAnyway: '自由に練習', resume: 'セッションを再開', courses: '教材', courseSingular: '件の教材', courseCount: '件の教材', cardSingular: '枚のカード', practicedToday: '今日学習したカード', deckLead: '優先度の高い項目から短いセッションで復習します。', browse: '質問を見る', browseLead: '質問を開くと答えと出典を確認できます。', sessionTitle: '復習セッション', pause: '一時停止', question: '質問', thinkFirst: '答えを表示する前に思い出してみましょう。', showAnswer: '答えを表示', ratePrompt: 'どれくらい覚えていましたか？', answerCount: '件の回答を評価', finishLead: '学習内容は保存されました。難しい項目は早めに再登場します。', openCourse: '教材を開く', openPdf: 'PDFのページを見る', noCoursesTitle: '最初の教材を追加しましょう。', noCoursesLead: 'PDFを追加してカードを作成すると復習を始められます。' },
  ar: { eyebrow: 'مساحة المراجعة', homeTitle: 'تبدأ جلستك من هنا.', homeLead: 'جُمعت الموضوعات المستحقة ورُتبت حسب الأولوية. ركّز على سؤال واحد في كل مرة.', readyTitle: 'أنت على المسار الصحيح.', readyLead: 'لا توجد بطاقات مستحقة الآن. يمكنك التدريب بحرية أو فتح مادة.', startToday: 'ابدأ المراجعة', practiceAnyway: 'تدرّب بحرية', resume: 'استأنف الجلسة', courses: 'موادي', courseSingular: 'مادة', courseCount: 'مواد', cardSingular: 'بطاقة', practicedToday: 'دُرست اليوم', deckLead: 'جلسة قصيرة تبدأ بالموضوعات الأشد حاجة للمراجعة.', browse: 'تصفّح الأسئلة', browseLead: 'افتح السؤال لعرض الإجابة والمصدر.', sessionTitle: 'جلسة المراجعة', pause: 'أوقف الجلسة مؤقتًا', question: 'سؤال', thinkFirst: 'حاول تذكّر الإجابة قبل إظهارها.', showAnswer: 'أظهر الإجابة', ratePrompt: 'ما مدى تذكّرك للإجابة؟', answerCount: 'إجابات قُيّمت', finishLead: 'حُفظ تقدّمك. ستعود الموضوعات الصعبة في وقت أقرب.', openCourse: 'افتح المادة', openPdf: 'اعرض صفحة PDF', noCoursesTitle: 'مساحة المراجعة جاهزة لأول مادة.', noCoursesLead: 'أضف ملف PDF وأنشئ بطاقات لبدء المراجعة.' },
}
