import type { StudyPdfLocale } from '@/lib/study-pdf-locales'

export const studyFlowCopy: Record<StudyPdfLocale, {
  savedCards: string; createCards: string; openCards: string; replaceWarning: string
  loadFailed: string; retry: string; quizInDocument: string; fromDocument: string
  reveal: string; markCard: string; finished: string; studyAgain: string; source: string
  resetProgress: string; resetConfirm: string; deleteCards: string; deleteConfirm: string; deleteFailed: string
}> = {
  fr: { savedCards: 'Cartes enregistrées', createCards: 'Créer des flashcards', openCards: 'Réviser les cartes', replaceWarning: 'Une nouvelle génération remplacera les cartes actuelles et leur progression.', loadFailed: 'Impossible de charger les cartes enregistrées.', retry: 'Réessayer', quizInDocument: 'Faire un quiz sur ce document', fromDocument: 'À partir du document', reveal: 'Afficher la réponse', markCard: 'Comment as-tu répondu ?', finished: 'Session terminée', studyAgain: 'Recommencer une session', source: 'Source', resetProgress: 'Réinitialiser la progression', resetConfirm: 'Les résultats de révision de ces cartes seront effacés.', deleteCards: 'Supprimer les cartes', deleteConfirm: 'Ces cartes seront supprimées définitivement. Le document restera disponible.', deleteFailed: 'Impossible de supprimer les cartes. Réessaie.' },
  en: { savedCards: 'Saved cards', createCards: 'Create flashcards', openCards: 'Study the cards', replaceWarning: 'Generating again replaces the current cards and their progress.', loadFailed: 'Could not load saved cards.', retry: 'Try again', quizInDocument: 'Take a quiz on this document', fromDocument: 'From the document', reveal: 'Show answer', markCard: 'How did you answer?', finished: 'Session complete', studyAgain: 'Start another session', source: 'Source', resetProgress: 'Reset progress', resetConfirm: 'Your study results for these cards will be cleared.', deleteCards: 'Delete cards', deleteConfirm: 'These cards will be permanently deleted. The document will remain available.', deleteFailed: 'Could not delete the cards. Try again.' },
  es: { savedCards: 'Tarjetas guardadas', createCards: 'Crear tarjetas', openCards: 'Repasar las tarjetas', replaceWarning: 'Una nueva generación sustituirá las tarjetas actuales y su progreso.', loadFailed: 'No se pudieron cargar las tarjetas guardadas.', retry: 'Reintentar', quizInDocument: 'Hacer un cuestionario de este documento', fromDocument: 'A partir del documento', reveal: 'Mostrar respuesta', markCard: '¿Cómo respondiste?', finished: 'Sesión terminada', studyAgain: 'Empezar otra sesión', source: 'Fuente', resetProgress: 'Reiniciar el progreso', resetConfirm: 'Se borrarán los resultados de repaso de estas tarjetas.', deleteCards: 'Eliminar tarjetas', deleteConfirm: 'Estas tarjetas se eliminarán definitivamente. El documento seguirá disponible.', deleteFailed: 'No se pudieron eliminar las tarjetas. Inténtalo de nuevo.' },
  de: { savedCards: 'Gespeicherte Karten', createCards: 'Karteikarten erstellen', openCards: 'Karten wiederholen', replaceWarning: 'Eine neue Erstellung ersetzt die bisherigen Karten und ihren Lernstand.', loadFailed: 'Gespeicherte Karten konnten nicht geladen werden.', retry: 'Erneut versuchen', quizInDocument: 'Quiz zu diesem Dokument starten', fromDocument: 'Aus dem Dokument', reveal: 'Antwort anzeigen', markCard: 'Wie war deine Antwort?', finished: 'Lerneinheit abgeschlossen', studyAgain: 'Neue Lerneinheit starten', source: 'Quelle', resetProgress: 'Lernstand zurücksetzen', resetConfirm: 'Die Lernergebnisse dieser Karten werden gelöscht.', deleteCards: 'Karten löschen', deleteConfirm: 'Diese Karten werden dauerhaft gelöscht. Das Dokument bleibt erhalten.', deleteFailed: 'Die Karten konnten nicht gelöscht werden. Bitte erneut versuchen.' },
  it: { savedCards: 'Schede salvate', createCards: 'Crea flashcard', openCards: 'Ripassa le schede', replaceWarning: 'Una nuova generazione sostituirà le schede attuali e i progressi.', loadFailed: 'Impossibile caricare le schede salvate.', retry: 'Riprova', quizInDocument: 'Fai un quiz su questo documento', fromDocument: 'Dal documento', reveal: 'Mostra la risposta', markCard: 'Come hai risposto?', finished: 'Sessione completata', studyAgain: 'Inizia un’altra sessione', source: 'Fonte', resetProgress: 'Azzera i progressi', resetConfirm: 'I risultati di studio di queste schede saranno cancellati.', deleteCards: 'Elimina schede', deleteConfirm: 'Queste schede saranno eliminate definitivamente. Il documento resterà disponibile.', deleteFailed: 'Impossibile eliminare le schede. Riprova.' },
  pt: { savedCards: 'Cartões guardados', createCards: 'Criar cartões', openCards: 'Rever cartões', replaceWarning: 'Uma nova geração substitui os cartões atuais e o seu progresso.', loadFailed: 'Não foi possível carregar os cartões guardados.', retry: 'Tentar novamente', quizInDocument: 'Fazer um questionário sobre este documento', fromDocument: 'A partir do documento', reveal: 'Mostrar resposta', markCard: 'Como respondeste?', finished: 'Sessão concluída', studyAgain: 'Começar outra sessão', source: 'Fonte', resetProgress: 'Repor o progresso', resetConfirm: 'Os resultados de estudo destes cartões serão apagados.', deleteCards: 'Eliminar cartões', deleteConfirm: 'Estes cartões serão eliminados definitivamente. O documento continuará disponível.', deleteFailed: 'Não foi possível eliminar os cartões. Tenta novamente.' },
  zh: { savedCards: '已保存的卡片', createCards: '创建记忆卡', openCards: '复习卡片', replaceWarning: '重新生成会替换现有卡片及其学习进度。', loadFailed: '无法加载已保存的卡片。', retry: '重试', quizInDocument: '练习这份文档的测验', fromDocument: '来自文档', reveal: '显示答案', markCard: '你的回答怎么样？', finished: '本轮复习完成', studyAgain: '开始新一轮', source: '来源', resetProgress: '重置学习进度', resetConfirm: '这些卡片的学习记录将被清除。', deleteCards: '删除卡片', deleteConfirm: '这些卡片将被永久删除，文档仍会保留。', deleteFailed: '无法删除卡片，请重试。' },
  ja: { savedCards: '保存済みカード', createCards: '単語カードを作成', openCards: 'カードで復習', replaceWarning: '再生成すると現在のカードと学習履歴が置き換わります。', loadFailed: '保存済みカードを読み込めませんでした。', retry: '再試行', quizInDocument: 'この文書のクイズに挑戦', fromDocument: '文書から作成', reveal: '答えを表示', markCard: '答えられましたか？', finished: '学習セッション完了', studyAgain: 'もう一度学習', source: '出典', resetProgress: '学習履歴をリセット', resetConfirm: 'これらのカードの学習結果を消去します。', deleteCards: 'カードを削除', deleteConfirm: 'これらのカードは完全に削除されます。文書は残ります。', deleteFailed: 'カードを削除できませんでした。再試行してください。' },
  ar: { savedCards: 'البطاقات المحفوظة', createCards: 'أنشئ بطاقات مراجعة', openCards: 'راجع البطاقات', replaceWarning: 'سيحل الإنشاء الجديد محل البطاقات الحالية وتقدمها.', loadFailed: 'تعذر تحميل البطاقات المحفوظة.', retry: 'حاول مجددًا', quizInDocument: 'ابدأ اختبارًا لهذا المستند', fromDocument: 'من المستند', reveal: 'أظهر الإجابة', markCard: 'كيف كانت إجابتك؟', finished: 'اكتملت الجلسة', studyAgain: 'ابدأ جلسة أخرى', source: 'المصدر', resetProgress: 'إعادة ضبط التقدم', resetConfirm: 'ستُمسح نتائج مراجعة هذه البطاقات.', deleteCards: 'حذف البطاقات', deleteConfirm: 'ستُحذف هذه البطاقات نهائيًا. سيبقى المستند متاحًا.', deleteFailed: 'تعذر حذف البطاقات. حاول مجددًا.' },
}

export const quizFlowCopy: Record<StudyPdfLocale, { freeCards: string; aiCost: string; history: string; sessions: string; average: string; recent: string }> = {
  fr: { freeCards: 'Depuis tes flashcards : sans nouvelle génération IA ni débit de pages.', aiCost: 'Nouvelles questions IA : utilise le quota de pages indiqué.', history: 'Questions à reprendre', sessions: 'Sessions', average: 'Score moyen', recent: 'Dernières sessions' },
  en: { freeCards: 'From your flashcards: no new AI generation or page charge.', aiCost: 'New AI questions use the shown page allowance.', history: 'Questions to revisit', sessions: 'Sessions', average: 'Average score', recent: 'Recent sessions' },
  es: { freeCards: 'Desde tus tarjetas: sin nueva generación con IA ni consumo de páginas.', aiCost: 'Las nuevas preguntas con IA usan el cupo de páginas indicado.', history: 'Preguntas para repasar', sessions: 'Sesiones', average: 'Puntuación media', recent: 'Sesiones recientes' },
  de: { freeCards: 'Aus deinen Karteikarten: ohne neue KI-Erstellung und ohne Seitenverbrauch.', aiCost: 'Neue KI-Fragen verbrauchen das angezeigte Seitenkontingent.', history: 'Fragen zum Wiederholen', sessions: 'Lerneinheiten', average: 'Durchschnittsergebnis', recent: 'Letzte Lerneinheiten' },
  it: { freeCards: 'Dalle tue flashcard: senza nuova generazione IA né consumo di pagine.', aiCost: 'Le nuove domande IA usano la quota di pagine indicata.', history: 'Domande da rivedere', sessions: 'Sessioni', average: 'Punteggio medio', recent: 'Sessioni recenti' },
  pt: { freeCards: 'A partir dos teus cartões: sem nova geração por IA nem gasto de páginas.', aiCost: 'As novas perguntas de IA usam a quota de páginas indicada.', history: 'Perguntas a rever', sessions: 'Sessões', average: 'Pontuação média', recent: 'Sessões recentes' },
  zh: { freeCards: '使用现有记忆卡：无需再次调用 AI，也不消耗页面额度。', aiCost: '新生成的 AI 题目会消耗所示页面额度。', history: '需要复习的题目', sessions: '学习次数', average: '平均得分', recent: '最近的练习' },
  ja: { freeCards: '保存済みカードから出題：新たなAI生成やページ枠の消費はありません。', aiCost: 'AIで新しい問題を作る場合は、表示されたページ枠を使用します。', history: '復習する問題', sessions: '学習回数', average: '平均スコア', recent: '最近の学習' },
  ar: { freeCards: 'من بطاقاتك المحفوظة: دون إنشاء جديد بالذكاء الاصطناعي أو خصم صفحات.', aiCost: 'الأسئلة الجديدة بالذكاء الاصطناعي تستخدم حصة الصفحات الموضحة.', history: 'أسئلة تحتاج إلى مراجعة', sessions: 'جلسات', average: 'متوسط النتيجة', recent: 'الجلسات الأخيرة' },
}
