export const STUDY_PDF_LOCALES = ['fr', 'en', 'es', 'de', 'it', 'pt', 'zh', 'ja', 'ar'] as const
export type StudyPdfLocale = typeof STUDY_PDF_LOCALES[number]

export const studyPdfCopyFailure: Record<StudyPdfLocale, string> = {
  fr: 'Impossible de copier le texte. Essaie le téléchargement.',
  en: 'Could not copy the text. Try downloading it instead.',
  es: 'No se pudo copiar el texto. Prueba a descargarlo.',
  de: 'Der Text konnte nicht kopiert werden. Lade ihn stattdessen herunter.',
  it: 'Impossibile copiare il testo. Prova a scaricarlo.',
  pt: 'Não foi possível copiar o texto. Experimenta descarregá-lo.',
  zh: '无法复制文字。请尝试下载。',
  ja: 'テキストをコピーできませんでした。ダウンロードをお試しください。',
  ar: 'تعذر نسخ النص. جرّب تنزيله بدلًا من ذلك.',
}

type Copy = {
  name: string; title: string; description: string; eyebrow: string; heading: string; intro: string
  home: string; study: string; choose: string; drop: string; limit: string; privacy: string
  checking: string; page: string; pages: string; readable: string; imageOnly: string; words: string
  ready: string; noText: string; partial: string; searchLabel: string; searchPlaceholder: string
  searchEmpty: string; resultCount: string; resultOne: string; openPage: string; copy: string; copied: string
  download: string; more: string; newFile: string; failure: string; invalid: string; tooLarge: string
  protected: string; empty: string; chapterTitle: string; chapterText: string; nextTitle: string
  nextText: string; nextAction: string; faqTitle: string; faqOne: string; faqAnswerOne: string
  faqTwo: string; faqAnswerTwo: string
}

export const studyPdfCopy: Record<StudyPdfLocale, Copy> = {
  fr: {
    name: 'Français', title: 'Extraire le texte d’un PDF et rechercher dans ses pages | CramDesk', description: 'Vérifie gratuitement si ton cours PDF contient du texte sélectionnable, cherche une notion par page et télécharge le texte. Sans compte ni transfert.',
    eyebrow: 'Outil gratuit pour les cours', heading: 'Explore le texte de ton PDF avant de réviser.', intro: 'Dépose un cours : repère les pages lisibles, retrouve une notion et exporte le texte. Tout se passe dans ton navigateur, sans compte.',
    home: 'Accueil', study: 'Réviser avec CramDesk', choose: 'Choisir un PDF', drop: 'Glisse ton cours PDF ici ou choisis un fichier', limit: 'PDF · 40 Mo maximum · 500 pages', privacy: 'Le fichier reste sur ton appareil. Aucune IA ni inscription.',
    checking: 'Lecture du document', page: 'Page', pages: 'pages', readable: 'avec du texte', imageOnly: 'sans texte détecté', words: 'mots détectés', ready: 'Le diagnostic est prêt.', noText: 'Aucun texte sélectionnable détecté. Ce PDF semble être un scan : cet outil ne fait pas d’OCR.', partial: 'Certaines pages ne contiennent pas de texte détectable. Vérifie-les dans le PDF original.',
    searchLabel: 'Chercher dans le cours', searchPlaceholder: 'Ex. photosynthèse, définition, théorème…', searchEmpty: 'Aucune page ne contient cette recherche.', resultCount: 'pages trouvées', resultOne: 'page trouvée', openPage: 'Voir la page', copy: 'Copier le texte', copied: 'Texte copié', download: 'Télécharger le texte', more: 'Voir plus de pages', newFile: 'Choisir un autre PDF', failure: 'Impossible de lire ce PDF. Essaie un autre fichier.', invalid: 'Choisis un fichier PDF valide.', tooLarge: 'Le fichier dépasse 40 Mo.', protected: 'Ce PDF est peut-être protégé ou endommagé.', empty: 'Ajoute un PDF pour voir ses pages et commencer une recherche.',
    chapterTitle: 'Du fichier au passage utile', chapterText: 'Cherche un terme de cours, ouvre la page correspondante et copie seulement le texte nécessaire. Les numéros de page suivent le PDF original.', nextTitle: 'Prêt à t’entraîner ?', nextText: 'Une fois ton PDF vérifié, le studio peut créer une synthèse, des cartes et un quiz liés à ton document. Cette étape utilise l’essai ou un forfait.', nextAction: 'Découvrir le studio', faqTitle: 'À savoir', faqOne: 'Est-ce que cet outil lit les PDF scannés ?', faqAnswerOne: 'Il signale les pages sans texte sélectionnable, mais ne reconnaît pas le texte d’une image. Il faut un PDF avec une couche texte ou un OCR externe.', faqTwo: 'Mon cours est-il envoyé à CramDesk ?', faqAnswerTwo: 'Non. Ce diagnostic, la recherche et l’export du texte s’exécutent dans ton navigateur. Seul un import volontaire dans le studio transmet ton fichier pour l’analyse IA.',
  },
  en: {
    name: 'English', title: 'Extract text from PDF and search every page | CramDesk', description: 'Check whether your course PDF has selectable text, search concepts by page and download the text. Free, on-device and no account required.',
    eyebrow: 'Free tool for course PDFs', heading: 'Explore your PDF text before you study.', intro: 'Drop in your course notes to see which pages contain readable text, find a concept and export the text. Everything runs in your browser.',
    home: 'Home', study: 'Study with CramDesk', choose: 'Choose a PDF', drop: 'Drop your course PDF here or choose a file', limit: 'PDF · 40 MB maximum · 500 pages', privacy: 'Your file stays on your device. No AI or sign-up.',
    checking: 'Reading document', page: 'Page', pages: 'pages', readable: 'with text', imageOnly: 'without detected text', words: 'words detected', ready: 'Your document check is ready.', noText: 'No selectable text was detected. This PDF may be a scan; this tool does not run OCR.', partial: 'Some pages have no detectable text. Check them in the original PDF.',
    searchLabel: 'Search the course', searchPlaceholder: 'E.g. photosynthesis, definition, theorem…', searchEmpty: 'No pages match this search.', resultCount: 'matching pages', resultOne: 'matching page', openPage: 'Open page', copy: 'Copy text', copied: 'Text copied', download: 'Download text', more: 'Show more pages', newFile: 'Choose another PDF', failure: 'Could not read this PDF. Try another file.', invalid: 'Choose a valid PDF file.', tooLarge: 'The file is larger than 40 MB.', protected: 'This PDF may be protected or damaged.', empty: 'Add a PDF to inspect its pages and start searching.',
    chapterTitle: 'From file to useful passage', chapterText: 'Search for a course term, open its page and copy the text you need. Page numbers match the original PDF.', nextTitle: 'Ready to practise?', nextText: 'After checking your PDF, the study workspace can create a summary, flashcards and a quiz grounded in your document. This step uses a trial or plan.', nextAction: 'Explore the studio', faqTitle: 'Good to know', faqOne: 'Does this tool read scanned PDFs?', faqAnswerOne: 'It flags pages without selectable text but cannot recognise words in an image. You need a text-based PDF or a separate OCR tool.', faqTwo: 'Is my course uploaded to CramDesk?', faqAnswerTwo: 'No. This check, search and text export run in your browser. Only a separate, voluntary studio import sends a file for AI analysis.',
  },
  es: {
    name: 'Español', title: 'Extraer texto de un PDF y buscar por página | CramDesk', description: 'Comprueba si tus apuntes en PDF tienen texto seleccionable, busca conceptos por página y descarga el texto. Gratis y sin subir el archivo.',
    eyebrow: 'Herramienta gratuita para estudiar', heading: 'Explora el texto de tu PDF antes de estudiar.', intro: 'Añade tus apuntes para saber qué páginas tienen texto, encontrar un concepto y exportar el contenido. Todo funciona en tu navegador.',
    home: 'Inicio', study: 'Estudiar con CramDesk', choose: 'Elegir un PDF', drop: 'Arrastra aquí tus apuntes en PDF o elige un archivo', limit: 'PDF · máximo 40 MB · 500 páginas', privacy: 'El archivo permanece en tu dispositivo. Sin IA ni registro.',
    checking: 'Leyendo el documento', page: 'Página', pages: 'páginas', readable: 'con texto', imageOnly: 'sin texto detectado', words: 'palabras detectadas', ready: 'El análisis del archivo está listo.', noText: 'No se detectó texto seleccionable. Puede ser un PDF escaneado; esta herramienta no aplica OCR.', partial: 'Algunas páginas no tienen texto detectable. Compruébalas en el PDF original.',
    searchLabel: 'Buscar en los apuntes', searchPlaceholder: 'Ej.: fotosíntesis, definición, teorema…', searchEmpty: 'Ninguna página coincide con la búsqueda.', resultCount: 'páginas encontradas', resultOne: 'página encontrada', openPage: 'Abrir página', copy: 'Copiar texto', copied: 'Texto copiado', download: 'Descargar texto', more: 'Ver más páginas', newFile: 'Elegir otro PDF', failure: 'No se pudo leer el PDF. Prueba con otro archivo.', invalid: 'Elige un archivo PDF válido.', tooLarge: 'El archivo supera los 40 MB.', protected: 'El PDF puede estar protegido o dañado.', empty: 'Añade un PDF para ver sus páginas y buscar contenido.',
    chapterTitle: 'Del archivo al fragmento útil', chapterText: 'Busca un concepto, abre la página correspondiente y copia el texto que necesites. La numeración coincide con el PDF original.', nextTitle: '¿Listo para practicar?', nextText: 'Después de comprobar el PDF, el espacio de estudio puede crear un resumen, tarjetas y un cuestionario basados en tu documento. Este paso utiliza una prueba o un plan.', nextAction: 'Descubrir el espacio de estudio', faqTitle: 'Información útil', faqOne: '¿Lee archivos PDF escaneados?', faqAnswerOne: 'Detecta páginas sin texto seleccionable, pero no reconoce palabras en imágenes. Necesitas un PDF con texto o una herramienta OCR aparte.', faqTwo: '¿Se envían mis apuntes a CramDesk?', faqAnswerTwo: 'No. La comprobación, la búsqueda y la exportación se realizan en tu navegador. Solo una importación voluntaria en el espacio de estudio envía el archivo para su análisis con IA.',
  },
  de: {
    name: 'Deutsch', title: 'Text aus PDF extrahieren und Seiten durchsuchen | CramDesk', description: 'Prüfe, ob dein Kurs-PDF auswählbaren Text enthält, suche Begriffe nach Seiten und lade den Text herunter. Kostenlos und lokal.',
    eyebrow: 'Kostenloses Werkzeug für Kurs-PDFs', heading: 'Durchsuche dein PDF, bevor du lernst.', intro: 'Füge deine Kursunterlagen hinzu: Erkenne lesbare Seiten, finde einen Begriff und exportiere den Text. Alles läuft in deinem Browser.',
    home: 'Startseite', study: 'Mit CramDesk lernen', choose: 'PDF auswählen', drop: 'Kurs-PDF hier ablegen oder Datei auswählen', limit: 'PDF · maximal 40 MB · 500 Seiten', privacy: 'Deine Datei bleibt auf deinem Gerät. Keine KI und keine Anmeldung.',
    checking: 'Dokument wird gelesen', page: 'Seite', pages: 'Seiten', readable: 'mit Text', imageOnly: 'ohne erkannten Text', words: 'Wörter erkannt', ready: 'Die Prüfung ist abgeschlossen.', noText: 'Kein auswählbarer Text erkannt. Dieses PDF könnte ein Scan sein; dieses Werkzeug bietet keine OCR.', partial: 'Einige Seiten enthalten keinen erkennbaren Text. Prüfe sie im Original-PDF.',
    searchLabel: 'Im Kurs suchen', searchPlaceholder: 'Z. B. Photosynthese, Definition, Theorem …', searchEmpty: 'Keine Seite entspricht dieser Suche.', resultCount: 'gefundene Seiten', resultOne: 'gefundene Seite', openPage: 'Seite öffnen', copy: 'Text kopieren', copied: 'Text kopiert', download: 'Text herunterladen', more: 'Weitere Seiten anzeigen', newFile: 'Anderes PDF auswählen', failure: 'Dieses PDF konnte nicht gelesen werden. Versuche eine andere Datei.', invalid: 'Wähle eine gültige PDF-Datei.', tooLarge: 'Die Datei ist größer als 40 MB.', protected: 'Dieses PDF ist möglicherweise geschützt oder beschädigt.', empty: 'Füge ein PDF hinzu, um Seiten zu prüfen und zu suchen.',
    chapterTitle: 'Von der Datei zur passenden Stelle', chapterText: 'Suche einen Fachbegriff, öffne die passende Seite und kopiere den benötigten Text. Die Seitenzahlen entsprechen dem Original-PDF.', nextTitle: 'Bereit zum Üben?', nextText: 'Nach der Prüfung deines PDFs kann der Lernbereich eine Zusammenfassung, Karteikarten und ein Quiz aus deinem Dokument erstellen. Dafür ist eine Probezeit oder ein Tarif nötig.', nextAction: 'Lernbereich entdecken', faqTitle: 'Gut zu wissen', faqOne: 'Kann das Werkzeug gescannte PDFs lesen?', faqAnswerOne: 'Es markiert Seiten ohne auswählbaren Text, erkennt aber keine Wörter in Bildern. Du brauchst ein Text-PDF oder ein separates OCR-Werkzeug.', faqTwo: 'Wird mein Kurs an CramDesk gesendet?', faqAnswerTwo: 'Nein. Prüfung, Suche und Textexport laufen im Browser. Nur ein freiwilliger Import in den Lernbereich sendet die Datei zur KI-Analyse.',
  },
  it: {
    name: 'Italiano', title: 'Estrarre testo da PDF e cercare nelle pagine | CramDesk', description: 'Controlla se il tuo PDF contiene testo selezionabile, cerca concetti per pagina e scarica il testo. Gratis e senza caricare il file.',
    eyebrow: 'Strumento gratuito per studiare', heading: 'Esplora il testo del tuo PDF prima di studiare.', intro: 'Aggiungi i tuoi appunti per vedere quali pagine contengono testo, trovare un concetto ed esportare il contenuto. Tutto avviene nel browser.',
    home: 'Home', study: 'Studia con CramDesk', choose: 'Scegli un PDF', drop: 'Trascina qui il PDF del corso o scegli un file', limit: 'PDF · massimo 40 MB · 500 pagine', privacy: 'Il file rimane sul tuo dispositivo. Nessuna IA o registrazione.',
    checking: 'Lettura del documento', page: 'Pagina', pages: 'pagine', readable: 'con testo', imageOnly: 'senza testo rilevato', words: 'parole rilevate', ready: 'La verifica è pronta.', noText: 'Non è stato rilevato testo selezionabile. Il PDF potrebbe essere una scansione; questo strumento non esegue OCR.', partial: 'Alcune pagine non contengono testo rilevabile. Controllale nel PDF originale.',
    searchLabel: 'Cerca negli appunti', searchPlaceholder: 'Es.: fotosintesi, definizione, teorema…', searchEmpty: 'Nessuna pagina corrisponde alla ricerca.', resultCount: 'pagine trovate', resultOne: 'pagina trovata', openPage: 'Apri pagina', copy: 'Copia testo', copied: 'Testo copiato', download: 'Scarica testo', more: 'Mostra altre pagine', newFile: 'Scegli un altro PDF', failure: 'Impossibile leggere il PDF. Prova un altro file.', invalid: 'Scegli un file PDF valido.', tooLarge: 'Il file supera i 40 MB.', protected: 'Il PDF potrebbe essere protetto o danneggiato.', empty: 'Aggiungi un PDF per controllare le pagine e cercare.',
    chapterTitle: 'Dal file al passaggio utile', chapterText: 'Cerca un termine, apri la pagina giusta e copia il testo necessario. I numeri di pagina corrispondono al PDF originale.', nextTitle: 'Pronto a esercitarti?', nextText: 'Dopo la verifica del PDF, lo spazio di studio può creare riassunto, schede e quiz basati sul documento. Questo passaggio richiede una prova o un piano.', nextAction: 'Scopri lo spazio di studio', faqTitle: 'Da sapere', faqOne: 'Questo strumento legge i PDF scansionati?', faqAnswerOne: 'Segnala le pagine senza testo selezionabile, ma non riconosce le parole nelle immagini. Serve un PDF testuale o uno strumento OCR separato.', faqTwo: 'I miei appunti vengono inviati a CramDesk?', faqAnswerTwo: 'No. Verifica, ricerca ed esportazione avvengono nel browser. Solo un import volontario nello spazio di studio invia il file per l’analisi IA.',
  },
  pt: {
    name: 'Português', title: 'Extrair texto de PDF e pesquisar por página | CramDesk', description: 'Verifica se o teu PDF de estudo tem texto selecionável, pesquisa conceitos por página e descarrega o texto. Grátis e sem envio.',
    eyebrow: 'Ferramenta gratuita para estudar', heading: 'Explora o texto do teu PDF antes de estudar.', intro: 'Adiciona os teus apontamentos para descobrir que páginas têm texto, encontrar um conceito e exportar o conteúdo. Tudo funciona no navegador.',
    home: 'Início', study: 'Estudar com CramDesk', choose: 'Escolher PDF', drop: 'Arrasta o PDF da disciplina para aqui ou escolhe um ficheiro', limit: 'PDF · máximo de 40 MB · 500 páginas', privacy: 'O ficheiro fica no teu dispositivo. Sem IA nem registo.',
    checking: 'A ler o documento', page: 'Página', pages: 'páginas', readable: 'com texto', imageOnly: 'sem texto detetado', words: 'palavras detetadas', ready: 'A verificação está pronta.', noText: 'Não foi detetado texto selecionável. Este PDF pode ser uma digitalização; esta ferramenta não faz OCR.', partial: 'Algumas páginas não têm texto detetável. Confirma-as no PDF original.',
    searchLabel: 'Pesquisar nos apontamentos', searchPlaceholder: 'Ex.: fotossíntese, definição, teorema…', searchEmpty: 'Nenhuma página corresponde à pesquisa.', resultCount: 'páginas encontradas', resultOne: 'página encontrada', openPage: 'Abrir página', copy: 'Copiar texto', copied: 'Texto copiado', download: 'Descarregar texto', more: 'Mostrar mais páginas', newFile: 'Escolher outro PDF', failure: 'Não foi possível ler este PDF. Experimenta outro ficheiro.', invalid: 'Escolhe um ficheiro PDF válido.', tooLarge: 'O ficheiro excede 40 MB.', protected: 'Este PDF pode estar protegido ou danificado.', empty: 'Adiciona um PDF para verificar as páginas e pesquisar.',
    chapterTitle: 'Do ficheiro ao excerto útil', chapterText: 'Pesquisa um termo, abre a página correspondente e copia o texto necessário. Os números correspondem ao PDF original.', nextTitle: 'Pronto para praticar?', nextText: 'Depois de verificares o PDF, o espaço de estudo pode criar um resumo, cartões e um questionário com base no documento. Este passo requer um período experimental ou plano.', nextAction: 'Explorar o espaço de estudo', faqTitle: 'Informações úteis', faqOne: 'Esta ferramenta lê PDF digitalizados?', faqAnswerOne: 'Assinala páginas sem texto selecionável, mas não reconhece palavras em imagens. Precisas de um PDF com texto ou de uma ferramenta OCR separada.', faqTwo: 'Os meus apontamentos são enviados para o CramDesk?', faqAnswerTwo: 'Não. A verificação, pesquisa e exportação decorrem no navegador. Apenas uma importação voluntária no espaço de estudo envia o ficheiro para análise por IA.',
  },
  zh: {
    name: '中文', title: '提取 PDF 文字并按页搜索 | CramDesk', description: '免费检查课程 PDF 是否包含可选文字，按页搜索知识点并下载文字。无需注册，文件不会上传。',
    eyebrow: '免费课程 PDF 工具', heading: '复习前，先看清 PDF 中的文字。', intro: '添加课程资料，查看哪些页面有可读取的文字，搜索知识点并导出文字。所有操作都在浏览器中完成。',
    home: '首页', study: '用 CramDesk 复习', choose: '选择 PDF', drop: '将课程 PDF 拖到这里，或选择文件', limit: 'PDF · 最大 40 MB · 500 页', privacy: '文件留在你的设备上。无需 AI 或注册。',
    checking: '正在读取文档', page: '页', pages: '页', readable: '页含文字', imageOnly: '页未检测到文字', words: '个词语', ready: '文档检查已完成。', noText: '未检测到可选文字。此 PDF 可能是扫描件；本工具不提供 OCR。', partial: '部分页面未检测到文字，请在原始 PDF 中核对。',
    searchLabel: '搜索课程内容', searchPlaceholder: '例如：光合作用、定义、定理…', searchEmpty: '没有页面符合此搜索。', resultCount: '个匹配页面', resultOne: '个匹配页面', openPage: '打开此页', copy: '复制文字', copied: '文字已复制', download: '下载文字', more: '显示更多页面', newFile: '选择其他 PDF', failure: '无法读取此 PDF，请尝试其他文件。', invalid: '请选择有效的 PDF 文件。', tooLarge: '文件超过 40 MB。', protected: '此 PDF 可能受密码保护或已损坏。', empty: '添加 PDF 后即可检查页面并搜索。',
    chapterTitle: '从文件找到有用的段落', chapterText: '搜索课程术语，打开对应页面，只复制所需文字。页码与原始 PDF 一致。', nextTitle: '准备好练习了吗？', nextText: '检查 PDF 后，学习空间可根据文档生成摘要、记忆卡和测验。此步骤需要试用或订阅。', nextAction: '了解学习空间', faqTitle: '常见问题', faqOne: '此工具能读取扫描版 PDF 吗？', faqAnswerOne: '它会标出没有可选文字的页面，但无法识别图片中的文字。请使用含文字层的 PDF，或另行使用 OCR 工具。', faqTwo: '课程文件会上传到 CramDesk 吗？', faqAnswerTwo: '不会。检查、搜索和文字导出均在浏览器中完成。只有主动导入学习空间时，文件才会用于 AI 分析。',
  },
  ja: {
    name: '日本語', title: 'PDFのテキストを抽出してページ別に検索 | CramDesk', description: '講義PDFに選択可能な文字があるか確認し、ページごとに用語を検索してテキストを保存。無料・登録不要・アップロード不要。',
    eyebrow: '講義PDF向け無料ツール', heading: '勉強を始める前に、PDFの文字を確認。', intro: '講義資料を追加すると、文字を読めるページを確認し、用語を探してテキストを書き出せます。処理はブラウザー内で完結します。',
    home: 'ホーム', study: 'CramDeskで学習', choose: 'PDFを選択', drop: '講義PDFをここにドロップするか、ファイルを選択', limit: 'PDF · 最大40 MB · 500ページ', privacy: 'ファイルは端末内に残ります。AIも登録も不要です。',
    checking: '文書を読み込み中', page: 'ページ', pages: 'ページ', readable: '文字あり', imageOnly: '文字を検出できないページ', words: '語を検出', ready: '文書の確認が完了しました。', noText: '選択可能な文字が見つかりません。スキャンPDFの可能性があります。このツールにはOCR機能はありません。', partial: '一部のページでは文字を検出できません。元のPDFで確認してください。',
    searchLabel: '講義資料を検索', searchPlaceholder: '例：光合成、定義、定理…', searchEmpty: '一致するページはありません。', resultCount: '件の一致ページ', resultOne: '件の一致ページ', openPage: 'ページを開く', copy: '文字をコピー', copied: 'コピーしました', download: 'テキストを保存', more: 'さらにページを表示', newFile: '別のPDFを選択', failure: 'このPDFを読めませんでした。別のファイルを試してください。', invalid: '有効なPDFファイルを選択してください。', tooLarge: 'ファイルが40 MBを超えています。', protected: 'PDFが保護されているか、破損している可能性があります。', empty: 'PDFを追加してページを確認し、検索を始めましょう。',
    chapterTitle: '必要な箇所をすぐに見つける', chapterText: '用語を検索して該当ページを開き、必要な文字だけコピーできます。ページ番号は元のPDFと一致します。', nextTitle: '次は理解度を試そう', nextText: 'PDFを確認したら、学習スペースで文書に基づく要約、単語カード、クイズを作成できます。この段階には試用またはプランが必要です。', nextAction: '学習スペースを見る', faqTitle: 'よくある質問', faqOne: 'スキャンPDFも読めますか？', faqAnswerOne: '選択可能な文字がないページを示しますが、画像内の文字は認識しません。文字入りPDFか別のOCRツールが必要です。', faqTwo: '講義資料はCramDeskに送信されますか？', faqAnswerTwo: 'いいえ。確認、検索、テキスト保存はブラウザー内で行われます。学習スペースへ自分で取り込んだ場合のみ、AI分析のために送信されます。',
  },
  ar: {
    name: 'العربية', title: 'استخراج النص من PDF والبحث حسب الصفحة | CramDesk', description: 'تحقق مجانًا من وجود نص قابل للتحديد في ملف المقرر، وابحث عن المفاهيم حسب الصفحة ونزّل النص. دون حساب أو رفع للملف.',
    eyebrow: 'أداة مجانية لملفات الدراسة', heading: 'استكشف نص ملف PDF قبل أن تبدأ المراجعة.', intro: 'أضف ملف المقرر لتعرف الصفحات التي تحتوي على نص، وابحث عن مفهوم وصدّر النص. تتم المعالجة بالكامل داخل متصفحك.',
    home: 'الرئيسية', study: 'راجع مع CramDesk', choose: 'اختر ملف PDF', drop: 'اسحب ملف المقرر هنا أو اختر ملفًا', limit: 'PDF · حتى 40 ميغابايت · 500 صفحة', privacy: 'يبقى الملف على جهازك. دون ذكاء اصطناعي أو تسجيل.',
    checking: 'جارٍ قراءة المستند', page: 'صفحة', pages: 'صفحات', readable: 'تحتوي على نص', imageOnly: 'بلا نص مكتشف', words: 'كلمات مكتشفة', ready: 'اكتمل فحص المستند.', noText: 'لم يُكتشف نص قابل للتحديد. قد يكون الملف ممسوحًا ضوئيًا؛ هذه الأداة لا توفر التعرف الضوئي على النص.', partial: 'بعض الصفحات لا تحتوي على نص يمكن اكتشافه. تحقق منها في ملف PDF الأصلي.',
    searchLabel: 'ابحث في المقرر', searchPlaceholder: 'مثل: التمثيل الضوئي، تعريف، نظرية…', searchEmpty: 'لا توجد صفحات تطابق البحث.', resultCount: 'صفحات مطابقة', resultOne: 'صفحة مطابقة', openPage: 'افتح الصفحة', copy: 'انسخ النص', copied: 'نُسخ النص', download: 'نزّل النص', more: 'اعرض صفحات أخرى', newFile: 'اختر ملف PDF آخر', failure: 'تعذرت قراءة هذا الملف. جرّب ملفًا آخر.', invalid: 'اختر ملف PDF صالحًا.', tooLarge: 'يتجاوز حجم الملف 40 ميغابايت.', protected: 'قد يكون الملف محميًا أو تالفًا.', empty: 'أضف ملف PDF لفحص الصفحات والبدء بالبحث.',
    chapterTitle: 'من الملف إلى المقطع المطلوب', chapterText: 'ابحث عن مصطلح دراسي، وافتح صفحته وانسخ النص الذي تحتاجه فقط. أرقام الصفحات تطابق الملف الأصلي.', nextTitle: 'هل أنت مستعد للتدرب؟', nextText: 'بعد فحص الملف، يمكن لمساحة الدراسة إنشاء ملخص وبطاقات واختبار مستندة إلى محتواه. تتطلب هذه الخطوة فترة تجريبية أو خطة.', nextAction: 'استكشف مساحة الدراسة', faqTitle: 'معلومات مهمة', faqOne: 'هل تقرأ الأداة ملفات PDF الممسوحة ضوئيًا؟', faqAnswerOne: 'تحدد الصفحات التي لا تحتوي على نص قابل للتحديد، لكنها لا تتعرف على الكلمات داخل الصور. تحتاج إلى ملف بطبقة نصية أو أداة OCR منفصلة.', faqTwo: 'هل يُرسل ملف المقرر إلى CramDesk؟', faqAnswerTwo: 'لا. يجري الفحص والبحث وتصدير النص داخل المتصفح. لا يُرسل الملف لتحليل الذكاء الاصطناعي إلا إذا استوردته بنفسك إلى مساحة الدراسة.',
  },
}

export function studyPdfPath(locale: StudyPdfLocale) {
  return locale === 'fr' ? '/extraire-texte-pdf' : `/${locale}/extract-text-from-pdf`
}
